# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `activerecord-explain-analyze` gem.
# Please instead update this file by running `bin/tapioca gem activerecord-explain-analyze`.

module ActiveRecordExplainAnalyze; end

module ActiveRecordExplainAnalyze::PostgreSQLAdapter
  def explain_with_options(arel, binds = T.unsafe(nil), analyze, format); end

  private

  def explain_pretty_printer; end
end

module ActiveRecordExplainAnalyze::Relation
  def exec_explain_with_options(queries, analyze:, format:); end
  def explain(analyze: T.unsafe(nil), format: T.unsafe(nil)); end
end

ActiveRecordExplainAnalyze::Relation::EXPLAIN_FORMATS = T.let(T.unsafe(nil), Array)
ActiveRecordExplainAnalyze::VERSION = T.let(T.unsafe(nil), String)
