# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `async` gem.
# Please instead update this file by running `bin/tapioca gem async`.


# pkg:gem/async#lib/async/version.rb:7
module Async; end

# A general purpose synchronisation primitive, which allows one task to wait for a number of other tasks to complete. It can be used in conjunction with {Semaphore}.
#
# pkg:gem/async#lib/async/barrier.rb:15
class Async::Barrier
  # Initialize the barrier.
  #
  # @return [Barrier] a new instance of Barrier
  #
  # pkg:gem/async#lib/async/barrier.rb:19
  def initialize(parent: T.unsafe(nil)); end

  # Execute a child task and add it to the barrier.
  #
  # pkg:gem/async#lib/async/barrier.rb:48
  def async(*arguments, parent: T.unsafe(nil), **options, &block); end

  # Cancel all tasks held by the barrier.
  #
  # pkg:gem/async#lib/async/barrier.rb:109
  def cancel; end

  # Whether there are any tasks being held by the barrier.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/barrier.rb:77
  def empty?; end

  # Number of tasks being held by the barrier.
  #
  # pkg:gem/async#lib/async/barrier.rb:38
  def size; end

  # Backward compatibility alias for {#cancel}.
  #
  # @deprecated Use {#cancel} instead.
  #
  # pkg:gem/async#lib/async/barrier.rb:119
  def stop; end

  # All tasks which have been invoked into the barrier.
  #
  # pkg:gem/async#lib/async/barrier.rb:43
  def tasks; end

  # Wait for all tasks to complete by invoking {Task#wait} on each waiting task, which may raise an error. As long as the task has completed, it will be removed from the barrier.
  #
  # pkg:gem/async#lib/async/barrier.rb:86
  def wait; end
end

# pkg:gem/async#lib/async/barrier.rb:27
class Async::Barrier::TaskNode < ::Async::List::Node
  # @return [TaskNode] a new instance of TaskNode
  #
  # pkg:gem/async#lib/async/barrier.rb:28
  def initialize(task); end

  # Returns the value of attribute task.
  #
  # pkg:gem/async#lib/async/barrier.rb:32
  def task; end
end

# Raised when a task is explicitly cancelled.
#
# pkg:gem/async#lib/async/cancel.rb:8
class Async::Cancel < ::Exception; end

# Represents the source of the cancel operation.
#
# pkg:gem/async#lib/async/cancel.rb:10
class Async::Cancel::Cause < ::Exception
  class << self
    # pkg:gem/async#lib/async/cancel.rb:13
    def backtrace; end

    # Create a new cause of the cancel operation, with the given message.
    #
    # pkg:gem/async#lib/async/cancel.rb:27
    def for(message = T.unsafe(nil)); end
  end
end

# Used to defer cancelling the current task until later.
#
# pkg:gem/async#lib/async/cancel.rb:59
class Async::Cancel::Later
  # Create a new cancel later operation.
  #
  # @return [Later] a new instance of Later
  #
  # pkg:gem/async#lib/async/cancel.rb:64
  def initialize(task, cause = T.unsafe(nil)); end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/cancel.rb:70
  def alive?; end

  # Transfer control to the operation - this will cancel the task.
  #
  # pkg:gem/async#lib/async/cancel.rb:75
  def transfer; end
end

# A list of children tasks.
#
# pkg:gem/async#lib/async/node.rb:15
class Async::Children < ::Async::List
  # Create an empty list of children tasks.
  #
  # @return [Children] a new instance of Children
  #
  # pkg:gem/async#lib/async/node.rb:17
  def initialize; end

  # Adjust the number of transient children, assuming it has changed.
  #
  # Despite being public, this is not intended to be called directly. It is used internally by {Node#transient=}.
  #
  # pkg:gem/async#lib/async/node.rb:43
  def adjust_transient_count(transient); end

  # Whether all children are considered finished. Ignores transient children.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/node.rb:29
  def finished?; end

  # Whether the children is empty, preserved for compatibility.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/node.rb:34
  def nil?; end

  # Some children may be marked as transient. Transient children do not prevent the parent from finishing.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/node.rb:24
  def transients?; end

  private

  # pkg:gem/async#lib/async/node.rb:53
  def added(node); end

  # pkg:gem/async#lib/async/node.rb:61
  def removed(node); end
end

# A convenient wrapper around the internal monotonic clock.
#
# pkg:gem/async#lib/async/clock.rb:10
class Async::Clock
  # Create a new clock with the initial total time.
  #
  # @return [Clock] a new instance of Clock
  #
  # pkg:gem/async#lib/async/clock.rb:35
  def initialize(total = T.unsafe(nil)); end

  # Convert the clock to a JSON-compatible hash.
  #
  # pkg:gem/async#lib/async/clock.rb:81
  def as_json(*_arg0, **_arg1, &_arg2); end

  # Reset the total elapsed time. If the clock is currently running, reset the start time to now.
  #
  # pkg:gem/async#lib/async/clock.rb:70
  def reset!; end

  # Start measuring a duration.
  #
  # pkg:gem/async#lib/async/clock.rb:44
  def start!; end

  # Returns the value of attribute started.
  #
  # pkg:gem/async#lib/async/clock.rb:41
  def started; end

  # Stop measuring a duration and append the duration to the current total.
  #
  # pkg:gem/async#lib/async/clock.rb:49
  def stop!; end

  # Convert the clock to a JSON string.
  #
  # pkg:gem/async#lib/async/clock.rb:91
  def to_json(*_arg0, **_arg1, &_arg2); end

  # The total elapsed time including any current duration.
  #
  # pkg:gem/async#lib/async/clock.rb:59
  def total; end

  class << self
    # Measure the execution of a block of code.
    #
    # pkg:gem/async#lib/async/clock.rb:19
    def measure; end

    # Get the current elapsed monotonic time.
    #
    # pkg:gem/async#lib/async/clock.rb:12
    def now; end

    # Start measuring elapsed time from now.
    #
    # pkg:gem/async#lib/async/clock.rb:29
    def start; end
  end
end

# A synchronization primitive, which allows fibers to wait until a particular condition is (edge) triggered.
#
# pkg:gem/async#lib/async/condition.rb:13
class Async::Condition
  # Create a new condition.
  #
  # @return [Condition] a new instance of Condition
  #
  # pkg:gem/async#lib/async/condition.rb:15
  def initialize; end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/condition.rb:26
  def empty?; end

  # Signal to a given task that it should resume operations.
  #
  # pkg:gem/async#lib/async/condition.rb:37
  def signal(value = T.unsafe(nil)); end

  # Queue up the current fiber and wait on yielding the task.
  #
  # pkg:gem/async#lib/async/condition.rb:21
  def wait; end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/condition.rb:31
  def waiting?; end

  protected

  # pkg:gem/async#lib/async/condition.rb:53
  def exchange; end
end

# Represents a deadline timeout with decrementing remaining time.
# Includes an efficient representation for zero (non-blocking) timeouts.
#
# pkg:gem/async#lib/async/deadline.rb:14
class Async::Deadline
  # Create a new deadline with the specified remaining time.
  #
  # @return [Deadline] a new instance of Deadline
  #
  # pkg:gem/async#lib/async/deadline.rb:46
  def initialize(remaining); end

  # Check if the deadline has expired.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/deadline.rb:67
  def expired?; end

  # Get the remaining time, updating internal state.
  # Each call to this method advances the internal clock and reduces
  # the remaining time by the elapsed duration since the last call.
  #
  # pkg:gem/async#lib/async/deadline.rb:55
  def remaining; end

  class << self
    # Create a deadline for the given timeout.
    #
    # pkg:gem/async#lib/async/deadline.rb:34
    def start(timeout); end
  end
end

# Singleton module for immediate timeouts (zero or negative).
# Avoids object allocation for fast path (non-blocking) timeouts.
#
# pkg:gem/async#lib/async/deadline.rb:17
module Async::Deadline::Zero
  class << self
    # Check if the deadline has expired.
    #
    # @return [Boolean]
    #
    # pkg:gem/async#lib/async/deadline.rb:20
    def expired?; end

    # Get the remaining time.
    #
    # pkg:gem/async#lib/async/deadline.rb:26
    def remaining; end
  end
end

# Private module that hooks into Process._fork to handle fork events.
#
# If `Scheduler#process_fork` hook is adopted in Ruby 4, this code can be removed after Ruby < 4 is no longer supported.
#
# pkg:gem/async#lib/async/fork_handler.rb:11
module Async::ForkHandler
  # pkg:gem/async#lib/async/fork_handler.rb:12
  def _fork(&block); end
end

# A load balancing mechanism that can be used process work when the system is idle.
#
# pkg:gem/async#lib/async/idler.rb:8
class Async::Idler
  # Create a new idler.
  #
  # @return [Idler] a new instance of Idler
  #
  # pkg:gem/async#lib/async/idler.rb:16
  def initialize(maximum_load = T.unsafe(nil), backoff: T.unsafe(nil), parent: T.unsafe(nil)); end

  # Wait until the system is idle, then execute the given block in a new task.
  #
  # pkg:gem/async#lib/async/idler.rb:33
  def async(*arguments, parent: T.unsafe(nil), **options, &block); end

  # Wait until the system is idle, according to the maximum load specified.
  #
  # If the scheduler is overloaded, this method will sleep for an exponentially increasing amount of time.
  #
  # pkg:gem/async#lib/async/idler.rb:43
  def wait; end
end

# A thread-safe queue which limits the number of items that can be enqueued.
#
# pkg:gem/async#lib/async/queue.rb:129
class Async::LimitedQueue < ::Async::Queue
  # Create a new limited queue.
  #
  # @return [LimitedQueue] a new instance of LimitedQueue
  #
  # pkg:gem/async#lib/async/queue.rb:141
  def initialize(limit = T.unsafe(nil), **options); end

  # pkg:gem/async#lib/async/queue.rb:146
  def limit; end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/queue.rb:151
  def limited?; end

  class << self
    # @private This exists purely for emitting a warning.
    #
    # pkg:gem/async#lib/async/queue.rb:131
    def new(*_arg0, **_arg1, &_arg2); end
  end
end

# A general doublely linked list. This is used internally by {Async::Barrier} and {Async::Condition} to manage child tasks.
#
# pkg:gem/async#lib/async/list.rb:9
class Async::List
  # Initialize a new, empty, list.
  #
  # @return [List] a new instance of List
  #
  # pkg:gem/async#lib/async/list.rb:11
  def initialize; end

  # A callback that is invoked when an item is added to the list.
  #
  # pkg:gem/async#lib/async/list.rb:51
  def added(node); end

  # Append a node to the end of the list.
  #
  # pkg:gem/async#lib/async/list.rb:57
  def append(node); end

  # Iterate over each node in the linked list. It is generally safe to remove the current node, any previous node or any future node during iteration.
  #
  # pkg:gem/async#lib/async/list.rb:177
  def each(&block); end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/list.rb:140
  def empty?; end

  # pkg:gem/async#lib/async/list.rb:198
  def first; end

  # Returns the value of attribute head.
  #
  # pkg:gem/async#lib/async/list.rb:42
  def head; end

  # Sets the attribute head
  #
  # @param value the value to set the attribute head to.
  #
  # pkg:gem/async#lib/async/list.rb:42
  def head=(_arg0); end

  # Determine whether the given node is included in the list.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/list.rb:189
  def include?(needle); end

  # pkg:gem/async#lib/async/list.rb:23
  def inspect; end

  # pkg:gem/async#lib/async/list.rb:215
  def last; end

  # Prepend a node to the start of the list.
  #
  # pkg:gem/async#lib/async/list.rb:71
  def prepend(node); end

  # Remove the node. If it was already removed, this will raise an error.
  #
  # You should be careful to only remove nodes that are part of this list.
  #
  # pkg:gem/async#lib/async/list.rb:119
  def remove(node); end

  # Remove the node if it is in a list.
  #
  # You should be careful to only remove nodes that are part of this list.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/list.rb:105
  def remove?(node); end

  # A callback that is invoked when an item is removed from the list.
  #
  # pkg:gem/async#lib/async/list.rb:95
  def removed(node); end

  # Shift the first node off the list, if it is not empty.
  #
  # pkg:gem/async#lib/async/list.rb:232
  def shift; end

  # Returns the value of attribute size.
  #
  # pkg:gem/async#lib/async/list.rb:48
  def size; end

  # Add the node, yield, and the remove the node.
  #
  # pkg:gem/async#lib/async/list.rb:87
  def stack(node, &block); end

  # Returns the value of attribute tail.
  #
  # pkg:gem/async#lib/async/list.rb:45
  def tail; end

  # Sets the attribute tail
  #
  # @param value the value to set the attribute tail to.
  #
  # pkg:gem/async#lib/async/list.rb:45
  def tail=(_arg0); end

  # Fast, safe, unbounded accumulation of children.
  #
  # pkg:gem/async#lib/async/list.rb:26
  def to_a; end

  # pkg:gem/async#lib/async/list.rb:18
  def to_s; end

  private

  # pkg:gem/async#lib/async/list.rb:128
  def remove!(node); end
end

# pkg:gem/async#lib/async/list.rb:252
class Async::List::Iterator < ::Async::List::Node
  # @return [Iterator] a new instance of Iterator
  #
  # pkg:gem/async#lib/async/list.rb:253
  def initialize(list); end

  # pkg:gem/async#lib/async/list.rb:296
  def each; end

  # pkg:gem/async#lib/async/list.rb:281
  def move_current; end

  # pkg:gem/async#lib/async/list.rb:271
  def move_next; end

  # pkg:gem/async#lib/async/list.rb:263
  def remove!; end

  class << self
    # pkg:gem/async#lib/async/list.rb:306
    def each(list, &block); end
  end
end

# A linked list Node.
#
# pkg:gem/async#lib/async/list.rb:239
class Async::List::Node
  # Returns the value of attribute head.
  #
  # pkg:gem/async#lib/async/list.rb:240
  def head; end

  # Sets the attribute head
  #
  # @param value the value to set the attribute head to.
  #
  # pkg:gem/async#lib/async/list.rb:240
  def head=(_arg0); end

  # pkg:gem/async#lib/async/list.rb:249
  def inspect; end

  # Returns the value of attribute tail.
  #
  # pkg:gem/async#lib/async/list.rb:241
  def tail; end

  # Sets the attribute tail
  #
  # @param value the value to set the attribute tail to.
  #
  # pkg:gem/async#lib/async/list.rb:241
  def tail=(_arg0); end

  # pkg:gem/async#lib/async/list.rb:244
  def to_s; end
end

# pkg:gem/async#lib/async/loop.rb:10
module Async::Loop
  class << self
    # Execute a block repeatedly with a fixed delay between executions.
    #
    # Unlike {quantized}, this method waits for the specified interval *after* each execution
    # completes. This means the actual time between the start of successive executions will be
    # `interval + execution_time`.
    #
    # If an error occurs during block execution, it is logged and the loop continues.
    #
    # @example Run every 5 seconds (plus execution time):
    #   Async::Loop.periodic(interval: 5) do
    #   process_queue
    #   end
    #
    # pkg:gem/async#lib/async/loop.rb:72
    def periodic(interval: T.unsafe(nil), &block); end

    # Execute a block repeatedly at quantized (time-aligned) intervals.
    #
    # The alignment is computed modulo the current clock time in seconds. For example, with
    # `interval: 60`, executions will occur at 00:00, 01:00, 02:00, etc., regardless of when
    # the loop is started. With `interval: 300` (5 minutes), executions align to 00:00, 00:05,
    # 00:10, etc.
    #
    # This is particularly useful for tasks that should run at predictable wall-clock times,
    # such as metrics collection, periodic cleanup, or scheduled jobs that need to align
    # across multiple processes.
    #
    # If an error occurs during block execution, it is logged and the loop continues.
    #
    # @example Run every 5 minutes aligned to the hour:
    #   Async::Loop.quantized(interval: 300) do
    #   collect_metrics
    #   end
    # @example Run every minute at :00 seconds:
    #   Async::Loop.quantized(interval: 60) do
    #   puts "Current time: #{Time.now}"
    #   end
    #
    # pkg:gem/async#lib/async/loop.rb:38
    def quantized(interval: T.unsafe(nil), &block); end
  end
end

# A node in a tree, used for implementing the task hierarchy.
#
# pkg:gem/async#lib/async/node.rb:71
class Async::Node
  # Create a new node in the tree.
  #
  # @return [Node] a new instance of Node
  #
  # pkg:gem/async#lib/async/node.rb:74
  def initialize(parent = T.unsafe(nil), annotation: T.unsafe(nil), transient: T.unsafe(nil)); end

  # Annotate the node with a description.
  #
  # pkg:gem/async#lib/async/node.rb:143
  def annotate(annotation); end

  # Returns the value of attribute annotation.
  #
  # pkg:gem/async#lib/async/node.rb:109
  def annotation; end

  # Provides a backtrace for nodes that have an active execution context.
  #
  # pkg:gem/async#lib/async/node.rb:175
  def backtrace(*arguments); end

  # Attempt to cancel the current node immediately, including all non-transient children. Invokes {#stop_children} to cancel all children.
  #
  # pkg:gem/async#lib/async/node.rb:286
  def cancel(later = T.unsafe(nil)); end

  # Whether the node has been cancelled.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/node.rb:311
  def cancelled?; end

  # Returns the value of attribute children.
  #
  # pkg:gem/async#lib/async/node.rb:106
  def children; end

  # Whether this node has any children.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/node.rb:113
  def children?; end

  # If the node has a parent, and is {finished?}, then remove this node from
  # the parent.
  #
  # pkg:gem/async#lib/async/node.rb:231
  def consume; end

  # A description of the node, including the annotation and object name.
  #
  # pkg:gem/async#lib/async/node.rb:160
  def description; end

  # Whether the node can be consumed (deleted) safely. By default, checks if the children set is empty.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/node.rb:225
  def finished?; end

  # @private
  #
  # pkg:gem/async#lib/async/node.rb:97
  def head; end

  # @private
  #
  # pkg:gem/async#lib/async/node.rb:97
  def head=(_arg0); end

  # pkg:gem/async#lib/async/node.rb:185
  def inspect; end

  # Returns the value of attribute parent.
  #
  # pkg:gem/async#lib/async/node.rb:103
  def parent; end

  # Change the parent of this node.
  #
  # pkg:gem/async#lib/async/node.rb:191
  def parent=(parent); end

  # Print the hierarchy of the task tree from the given node.
  #
  # pkg:gem/async#lib/async/node.rb:325
  def print_hierarchy(out = T.unsafe(nil), backtrace: T.unsafe(nil)); end

  # pkg:gem/async#lib/async/node.rb:92
  def root; end

  # Backward compatibility alias for {#cancel}.
  #
  # @deprecated Use {#cancel} instead.
  #
  # pkg:gem/async#lib/async/node.rb:293
  def stop(*_arg0, **_arg1, &_arg2); end

  # Backward compatibility alias for {#cancelled?}.
  #
  # @deprecated Use {#cancelled?} instead.
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/node.rb:317
  def stopped?; end

  # @private
  #
  # pkg:gem/async#lib/async/node.rb:100
  def tail; end

  # @private
  #
  # pkg:gem/async#lib/async/node.rb:100
  def tail=(_arg0); end

  # Immediately terminate all children tasks, including transient tasks. Internally invokes `stop(false)` on all children. This should be considered a last ditch effort and is used when closing the scheduler.
  #
  # pkg:gem/async#lib/async/node.rb:271
  def terminate; end

  # pkg:gem/async#lib/async/node.rb:180
  def to_s; end

  # Change the transient state of the node.
  #
  # A transient node is not considered when determining if a node is finished, and propagates up if the parent is consumed.
  #
  # pkg:gem/async#lib/async/node.rb:132
  def transient=(value); end

  # Represents whether a node is transient. Transient nodes are not considered
  # when determining if a node is finished. This is useful for tasks which are
  # internal to an object rather than explicit user concurrency. For example,
  # a child task which is pruning a connection pool is transient, because it
  # is not directly related to the parent task, and should not prevent the
  # parent task from finishing.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/node.rb:123
  def transient?; end

  # Traverse the task tree.
  #
  # pkg:gem/async#lib/async/node.rb:256
  def traverse(&block); end

  # Wait for this node to complete. By default, nodes cannot be waited on.
  # Subclasses like Task override this method to provide waiting functionality.
  #
  # pkg:gem/async#lib/async/node.rb:306
  def wait; end

  protected

  # pkg:gem/async#lib/async/node.rb:210
  def add_child(child); end

  # pkg:gem/async#lib/async/node.rb:216
  def remove_child(child); end

  # pkg:gem/async#lib/async/node.rb:206
  def set_parent(parent); end

  # @yield [_self, level]
  # @yieldparam _self [Async::Node] the object that the method was called on
  #
  # pkg:gem/async#lib/async/node.rb:262
  def traverse_recurse(level = T.unsafe(nil), &block); end

  private

  # pkg:gem/async#lib/async/node.rb:337
  def print_backtrace(out, indent, node); end

  # Attempt to stop all non-transient children.
  #
  # pkg:gem/async#lib/async/node.rb:298
  def stop_children(later = T.unsafe(nil)); end
end

# A synchronization primitive, which allows fibers to wait until a notification is received. Does not block the task which signals the notification. Waiting tasks are resumed on next iteration of the reactor.
#
# pkg:gem/async#lib/async/notification.rb:11
class Async::Notification < ::Async::Condition
  # Signal to a given task that it should resume operations.
  #
  # pkg:gem/async#lib/async/notification.rb:15
  def signal(value = T.unsafe(nil)); end
end

# pkg:gem/async#lib/async/notification.rb:23
class Async::Notification::Signal < ::Struct
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/notification.rb:24
  def alive?; end

  # Returns the value of attribute ready
  #
  # @return [Object] the current value of ready
  #
  # pkg:gem/async#lib/async/notification.rb:23
  def ready; end

  # Sets the attribute ready
  #
  # @param value [Object] the value to set the attribute ready to.
  # @return [Object] the newly set value
  #
  # pkg:gem/async#lib/async/notification.rb:23
  def ready=(_); end

  # pkg:gem/async#lib/async/notification.rb:28
  def transfer; end

  # Returns the value of attribute value
  #
  # @return [Object] the current value of value
  #
  # pkg:gem/async#lib/async/notification.rb:23
  def value; end

  # Sets the attribute value
  #
  # @param value [Object] the value to set the attribute value to.
  # @return [Object] the newly set value
  #
  # pkg:gem/async#lib/async/notification.rb:23
  def value=(_); end

  class << self
    # pkg:gem/async#lib/async/notification.rb:23
    def [](*_arg0); end

    # pkg:gem/async#lib/async/notification.rb:23
    def inspect; end

    # pkg:gem/async#lib/async/notification.rb:23
    def keyword_init?; end

    # pkg:gem/async#lib/async/notification.rb:23
    def members; end

    # pkg:gem/async#lib/async/notification.rb:23
    def new(*_arg0); end
  end
end

# pkg:gem/async#lib/async/scheduler.rb:25
Async::Profiler = T.let(T.unsafe(nil), T.untyped)

# A promise represents a value that will be available in the future.
# Unlike Condition, once resolved (or rejected), all future waits return immediately
# with the stored value or raise the stored exception.
#
# This is thread-safe and integrates with the fiber scheduler.
#
# pkg:gem/async#lib/async/promise.rb:19
class Async::Promise
  # Create a new promise.
  #
  # @return [Promise] a new instance of Promise
  #
  # pkg:gem/async#lib/async/promise.rb:21
  def initialize; end

  # Cancel the promise, indicating cancellation.
  # All current and future waiters will receive nil.
  # Can only be called on pending promises - no-op if already resolved.
  #
  # pkg:gem/async#lib/async/promise.rb:211
  def cancel(exception = T.unsafe(nil)); end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/promise.rb:47
  def cancelled?; end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/promise.rb:57
  def completed?; end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/promise.rb:52
  def failed?; end

  # Resolve the promise with the result of the block.
  # If the block raises an exception, the promise will be rejected.
  # If the promise was already resolved, the block will not be called.
  #
  # pkg:gem/async#lib/async/promise.rb:231
  def fulfill(&block); end

  # Reject the promise with an exception.
  # All current and future waiters will receive this exception.
  # Can only be called once - subsequent calls are ignored.
  #
  # pkg:gem/async#lib/async/promise.rb:194
  def reject(exception); end

  # Resolve the promise with a value.
  # All current and future waiters will receive this value.
  # Can only be called once - subsequent calls are ignored.
  #
  # pkg:gem/async#lib/async/promise.rb:175
  def resolve(value); end

  # @private For internal use by Task.
  #
  # pkg:gem/async#lib/async/promise.rb:42
  def resolved; end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/promise.rb:36
  def resolved?; end

  # Artificially mark that someone is waiting (useful for suppressing warnings).
  #
  # @private Internal use only.
  #
  # pkg:gem/async#lib/async/promise.rb:68
  def suppress_warnings!; end

  # Non-blocking access to the current value. Returns nil if not yet resolved.
  # Does not raise exceptions even if the promise was rejected or cancelled.
  # For resolved promises, returns the raw stored value (result, exception, or cancel exception).
  #
  # pkg:gem/async#lib/async/promise.rb:77
  def value; end

  # Wait for the promise to be resolved and return the value.
  #
  # If already resolved, returns immediately. If rejected, raises the stored exception.
  #
  # pkg:gem/async#lib/async/promise.rb:157
  def wait(*_arg0, **_arg1, &_arg2); end

  # Wait for the promise to be resolved (without raising exceptions).
  #
  # If already resolved, returns immediately. Otherwise, waits until resolution or timeout.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/promise.rb:122
  def wait?(timeout: T.unsafe(nil)); end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/promise.rb:62
  def waiting?; end

  private

  # Wait indefinitely for the promise to be resolved.
  #
  # pkg:gem/async#lib/async/promise.rb:82
  def wait_indefinitely; end

  # Wait for the promise to be resolved, respecting the deadline timeout.
  #
  # pkg:gem/async#lib/async/promise.rb:91
  def wait_with_timeout(timeout); end

  class << self
    # If a promise is given, fulfill it with the result of the block.
    # If no promise is given, simply yield to the block.
    # This is useful for methods that may optionally take a promise to fulfill.
    #
    # pkg:gem/async#lib/async/promise.rb:255
    def fulfill(promise, &block); end
  end
end

# A thread-safe queue which allows items to be processed in order.
#
# This implementation uses Thread::Queue internally for thread safety while
# maintaining compatibility with the fiber scheduler.
#
# It has a compatible interface with {Notification} and {Condition}, except that it's multi-value.
#
# pkg:gem/async#lib/async/queue.rb:22
class Async::Queue
  # Create a new thread-safe queue.
  #
  # @return [Queue] a new instance of Queue
  #
  # pkg:gem/async#lib/async/queue.rb:31
  def initialize(parent: T.unsafe(nil), delegate: T.unsafe(nil)); end

  # Compatibility with {::Queue#push}.
  #
  # pkg:gem/async#lib/async/queue.rb:69
  def <<(item); end

  # Process each item in the queue.
  #
  # pkg:gem/async#lib/async/queue.rb:102
  def async(parent: T.unsafe(nil), **options, &block); end

  # Close the queue, causing all waiting tasks to return `nil`. Any subsequent calls to {enqueue} will raise an exception.
  #
  # pkg:gem/async#lib/async/queue.rb:42
  def close; end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/queue.rb:37
  def closed?; end

  # Remove and return the next item from the queue.
  #
  # pkg:gem/async#lib/async/queue.rb:83
  def dequeue(timeout: T.unsafe(nil)); end

  # Enumerate each item in the queue.
  #
  # pkg:gem/async#lib/async/queue.rb:109
  def each; end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/queue.rb:52
  def empty?; end

  # Add multiple items to the queue.
  #
  # pkg:gem/async#lib/async/queue.rb:74
  def enqueue(*items); end

  # Compatibility with {::Queue#pop}.
  #
  # pkg:gem/async#lib/async/queue.rb:90
  def pop(timeout: T.unsafe(nil)); end

  # Add an item to the queue.
  #
  # pkg:gem/async#lib/async/queue.rb:62
  def push(item); end

  # Signal the queue with a value, the same as {#enqueue}.
  #
  # pkg:gem/async#lib/async/queue.rb:116
  def signal(value = T.unsafe(nil)); end

  # pkg:gem/async#lib/async/queue.rb:47
  def size; end

  # Wait for an item to be available, the same as {#dequeue}.
  #
  # pkg:gem/async#lib/async/queue.rb:121
  def wait; end

  # pkg:gem/async#lib/async/queue.rb:57
  def waiting_count; end
end

# An error raised when trying to enqueue items to a closed queue.
#
# pkg:gem/async#lib/async/queue.rb:25
class Async::Queue::ClosedError < ::RuntimeError; end

# A wrapper around the the scheduler which binds it to the current thread automatically.
#
# pkg:gem/async#lib/async/reactor.rb:12
class Async::Reactor < ::Async::Scheduler
  # Initialize the reactor and assign it to the current Fiber scheduler.
  #
  # @return [Reactor] a new instance of Reactor
  #
  # pkg:gem/async#lib/async/reactor.rb:21
  def initialize(*_arg0, **_arg1, &_arg2); end

  # Close the reactor and remove it from the current Fiber scheduler.
  #
  # pkg:gem/async#lib/async/reactor.rb:28
  def scheduler_close; end

  # pkg:gem/async#lib/async/reactor.rb:32
  def sleep(*_arg0); end

  class << self
    # @deprecated Replaced by {Kernel::Async}.
    #
    # pkg:gem/async#lib/async/reactor.rb:14
    def run(*_arg0, **_arg1, &_arg2); end
  end
end

# Handles scheduling of fibers. Implements the fiber scheduler interface.
#
# pkg:gem/async#lib/async/scheduler.rb:29
class Async::Scheduler < ::Async::Node
  # Create a new scheduler.
  #
  # @return [Scheduler] a new instance of Scheduler
  #
  # pkg:gem/async#lib/async/scheduler.rb:77
  def initialize(parent = T.unsafe(nil), selector: T.unsafe(nil), profiler: T.unsafe(nil), worker_pool: T.unsafe(nil)); end

  # Resolve the address of the given hostname.
  #
  # pkg:gem/async#lib/async/scheduler.rb:294
  def address_resolve(hostname); end

  # Start an asynchronous task within the specified reactor. The task will be executed until the first blocking call, at which point it will yield and and this method will return.
  #
  # @deprecated Use {#run} or {Task#async} instead.
  #
  # pkg:gem/async#lib/async/scheduler.rb:593
  def async(*arguments, **options, &block); end

  # Invoked when a fiber tries to perform a blocking operation which cannot continue. A corresponding call {unblock} must be performed to allow this fiber to continue.
  #
  # pkg:gem/async#lib/async/scheduler.rb:233
  def block(blocker, timeout); end

  # Cancel all children, including transient children.
  #
  # pkg:gem/async#lib/async/scheduler.rb:517
  def cancel; end

  # Terminate all child tasks and close the scheduler.
  #
  # pkg:gem/async#lib/async/scheduler.rb:149
  def close; end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/scheduler.rb:176
  def closed?; end

  # Create a new fiber and return it without starting execution.
  #
  # pkg:gem/async#lib/async/scheduler.rb:608
  def fiber(*_arg0, **_arg1, &_arg2); end

  # Raise an exception on the specified fiber, waking up the event loop if necessary.
  #
  # pkg:gem/async#lib/async/scheduler.rb:402
  def fiber_interrupt(fiber, exception); end

  # Interrupt the event loop and cause it to exit.
  #
  # pkg:gem/async#lib/async/scheduler.rb:187
  def interrupt; end

  # Read from the specified IO into the buffer.
  #
  # pkg:gem/async#lib/async/scheduler.rb:339
  def io_read(io, buffer, length, offset = T.unsafe(nil)); end

  # Wait for the specified IOs to become ready for the specified events.
  #
  # pkg:gem/async#lib/async/scheduler.rb:424
  def io_select(*_arg0, **_arg1, &_arg2); end

  # Wait for the specified IO to become ready for the specified events.
  #
  # pkg:gem/async#lib/async/scheduler.rb:309
  def io_wait(io, events, timeout = T.unsafe(nil)); end

  # Write the specified buffer to the IO.
  #
  # pkg:gem/async#lib/async/scheduler.rb:363
  def io_write(io, buffer, length, offset = T.unsafe(nil)); end

  # Sleep for the specified duration.
  #
  # pkg:gem/async#lib/async/scheduler.rb:278
  def kernel_sleep(duration = T.unsafe(nil)); end

  # Compute the scheduler load according to the busy and idle times that are updated by the run loop.
  #
  # pkg:gem/async#lib/async/scheduler.rb:106
  def load; end

  # Handle fork in the child process. This method is called automatically when `Process.fork` is invoked on Ruby versions < 4 and cleans up the scheduler state. On Ruby 4+, the scheduler is automatically cleaned up by the Ruby runtime.
  #
  # The child process starts with a clean slate - no scheduler is set. Users can create a new scheduler if needed.
  #
  # pkg:gem/async#lib/async/scheduler.rb:659
  def process_fork; end

  # Wait for the specified process ID to exit.
  #
  # pkg:gem/async#lib/async/scheduler.rb:416
  def process_wait(pid, flags); end

  # Schedule a fiber (or equivalent object) to be resumed on the next loop through the reactor.
  #
  # pkg:gem/async#lib/async/scheduler.rb:204
  def push(fiber); end

  # Raise an exception on a specified fiber with the given arguments.
  #
  # This internally schedules the current fiber to be ready, before raising the exception, so that it will later resume execution.
  #
  # pkg:gem/async#lib/async/scheduler.rb:214
  def raise(*_arg0, **_arg1, &_arg2); end

  # Resume execution of the specified fiber.
  #
  # pkg:gem/async#lib/async/scheduler.rb:222
  def resume(fiber, *arguments); end

  # Run the reactor until all tasks are finished. Proxies arguments to {#async} immediately before entering the loop, if a block is provided.
  #
  # Forwards all parameters to {#async} if a block is given.
  #
  # pkg:gem/async#lib/async/scheduler.rb:567
  def run(*_arg0, **_arg1, &_arg2); end

  # Run one iteration of the event loop.
  #
  # pkg:gem/async#lib/async/scheduler.rb:483
  def run_once(timeout = T.unsafe(nil)); end

  # Invoked when the fiber scheduler is being closed.
  #
  # Executes the run loop until all tasks are finished, then closes the scheduler.
  #
  # pkg:gem/async#lib/async/scheduler.rb:128
  def scheduler_close(error = T.unsafe(nil)); end

  # Backward compatibility alias for cancel.
  #
  # pkg:gem/async#lib/async/scheduler.rb:524
  def stop; end

  # Terminate all child tasks.
  #
  # pkg:gem/async#lib/async/scheduler.rb:138
  def terminate; end

  # Invoke the block, but after the specified timeout, raise the specified exception with the given message. If the block runs to completion before the timeout occurs or there are no non-blocking operations after the timeout expires, the code will complete without any exception.
  #
  # pkg:gem/async#lib/async/scheduler.rb:648
  def timeout_after(duration, exception, message, &block); end

  # pkg:gem/async#lib/async/scheduler.rb:181
  def to_s; end

  # Transfer from the calling fiber to the event loop.
  #
  # pkg:gem/async#lib/async/scheduler.rb:193
  def transfer; end

  # Unblock a fiber that was previously blocked.
  #
  # pkg:gem/async#lib/async/scheduler.rb:262
  def unblock(blocker, fiber); end

  # Invoke the block, but after the specified timeout, raise {TimeoutError} in any currenly blocking operation. If the block runs to completion before the timeout occurs or there are no non-blocking operations after the timeout expires, the code will complete without any exception.
  #
  # pkg:gem/async#lib/async/scheduler.rb:621
  def with_timeout(duration, exception = T.unsafe(nil), message = T.unsafe(nil), &block); end

  # Yield the current fiber and resume it on the next iteration of the event loop.
  #
  # pkg:gem/async#lib/async/scheduler.rb:198
  def yield; end

  private

  # Checks and clears the interrupted state of the scheduler.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/scheduler.rb:501
  def interrupted?; end

  # pkg:gem/async#lib/async/scheduler.rb:528
  def run_loop(&block); end

  # Run one iteration of the event loop.
  #
  # When terminating the event loop, we already know we are finished. So we don't need to check the task tree. This is a logical requirement because `run_once` ignores transient tasks. For example, a single top level transient task is not enough to keep the reactor running, but during termination we must still process it in order to terminate child tasks.
  #
  # pkg:gem/async#lib/async/scheduler.rb:439
  def run_once!(timeout = T.unsafe(nil)); end

  class << self
    # Whether the fiber scheduler is supported.
    #
    # @return [Boolean]
    #
    # pkg:gem/async#lib/async/scheduler.rb:46
    def supported?; end
  end
end

# Used to augment the scheduler to add support for blocking operations.
#
# pkg:gem/async#lib/async/scheduler.rb:51
module Async::Scheduler::BlockingOperationWait
  # Wait for the given work to be executed.
  #
  # pkg:gem/async#lib/async/scheduler.rb:59
  def blocking_operation_wait(work); end
end

# Raised when an operation is attempted on a closed scheduler.
#
# pkg:gem/async#lib/async/scheduler.rb:35
class Async::Scheduler::ClosedError < ::RuntimeError
  # Create a new error.
  #
  # @return [ClosedError] a new instance of ClosedError
  #
  # pkg:gem/async#lib/async/scheduler.rb:39
  def initialize(message = T.unsafe(nil)); end
end

# Used to defer stopping the current task until later.
#
# pkg:gem/async#lib/async/scheduler.rb:380
class Async::Scheduler::FiberInterrupt
  # Create a new stop later operation.
  #
  # @return [FiberInterrupt] a new instance of FiberInterrupt
  #
  # pkg:gem/async#lib/async/scheduler.rb:384
  def initialize(fiber, exception); end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/scheduler.rb:390
  def alive?; end

  # Transfer control to the operation - this will stop the task.
  #
  # pkg:gem/async#lib/async/scheduler.rb:395
  def transfer; end
end

# pkg:gem/async#lib/async/scheduler.rb:30
Async::Scheduler::WORKER_POOL = T.let(T.unsafe(nil), T.untyped)

# pkg:gem/async#lib/async/scheduler.rb:67
Async::Scheduler::WorkerPool = IO::Event::WorkerPool

# A synchronization primitive, which limits access to a given resource.
#
# pkg:gem/async#lib/async/semaphore.rb:11
class Async::Semaphore
  # @return [Semaphore] a new instance of Semaphore
  #
  # pkg:gem/async#lib/async/semaphore.rb:14
  def initialize(limit = T.unsafe(nil), parent: T.unsafe(nil)); end

  # Acquire the semaphore, block if we are at the limit.
  # If no block is provided, you must call release manually.
  #
  # pkg:gem/async#lib/async/semaphore.rb:79
  def acquire; end

  # Run an async task. Will wait until the semaphore is ready until spawning and running the task.
  #
  # pkg:gem/async#lib/async/semaphore.rb:61
  def async(*arguments, parent: T.unsafe(nil), **options); end

  # Whether trying to acquire this semaphore would block.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/semaphore.rb:56
  def blocking?; end

  # The current number of tasks that have acquired the semaphore.
  #
  # pkg:gem/async#lib/async/semaphore.rb:23
  def count; end

  # Is the semaphore currently acquired?
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/semaphore.rb:51
  def empty?; end

  # The maximum number of tasks that can acquire the semaphore.
  #
  # pkg:gem/async#lib/async/semaphore.rb:26
  def limit; end

  # Allow setting the limit. This is useful for cases where the semaphore is used to limit the number of concurrent tasks, but the number of tasks is not known in advance or needs to be modified.
  #
  # On increasing the limit, some tasks may be immediately resumed. On decreasing the limit, some tasks may execute until the count is < than the limit.
  #
  # pkg:gem/async#lib/async/semaphore.rb:36
  def limit=(limit); end

  # Release the semaphore. Must match up with a corresponding call to `acquire`. Will release waiting fibers in FIFO order.
  #
  # pkg:gem/async#lib/async/semaphore.rb:94
  def release; end

  # The tasks waiting on this semaphore.
  #
  # pkg:gem/async#lib/async/semaphore.rb:29
  def waiting; end

  private

  # Wait until the semaphore becomes available.
  #
  # pkg:gem/async#lib/async/semaphore.rb:119
  def wait; end
end

# pkg:gem/async#lib/async/semaphore.rb:104
class Async::Semaphore::FiberNode < ::Async::List::Node
  # @return [FiberNode] a new instance of FiberNode
  #
  # pkg:gem/async#lib/async/semaphore.rb:105
  def initialize(fiber); end

  # pkg:gem/async#lib/async/semaphore.rb:109
  def resume; end
end

# pkg:gem/async#lib/async/stop.rb:9
Async::Stop = Async::Cancel

# Represents a sequential unit of work, defined by a block, which is executed concurrently with other tasks. A task can be in one of the following states: `initialized`, `running`, `completed`, `failed`, or `cancelled`.
#
# ```mermaid
# stateDiagram-v2
# [*] --> Initialized
# Initialized --> Running : Run
#
# Running --> Completed : Return Value
# Running --> Failed : Exception
#
# Completed --> [*]
# Failed --> [*]
#
# Running --> Cancelled : Cancel
# Cancelled --> [*]
# Completed --> Cancelled : Cancel
# Failed --> Cancelled : Cancel
# Initialized --> Cancelled : Cancel
# ```
#
# @example Creating a task that sleeps for 1 second.
#   require "async"
#   Async do |task|
#   sleep(1)
#   end
#
# pkg:gem/async#lib/async/task.rb:51
class Async::Task < ::Async::Node
  # Create a new task.
  #
  # @return [Task] a new instance of Task
  #
  # pkg:gem/async#lib/async/task.rb:79
  def initialize(parent = T.unsafe(nil), finished: T.unsafe(nil), **options, &block); end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/task.rb:165
  def alive?; end

  # Annotate the task with a description.
  #
  # This will internally try to annotate the fiber if it is running, otherwise it will annotate the task itself.
  #
  # pkg:gem/async#lib/async/task.rb:122
  def annotate(annotation, &block); end

  # pkg:gem/async#lib/async/task.rb:131
  def annotation; end

  # Run an asynchronous task as a child of the current task.
  #
  # @raise [FinishedError]
  #
  # pkg:gem/async#lib/async/task.rb:246
  def async(*arguments, **options, &block); end

  # pkg:gem/async#lib/async/task.rb:113
  def backtrace(*arguments); end

  # Cancel the task and all of its children.
  #
  # If `later` is false, it means that `cancel` has been invoked directly. When `later` is true, it means that `cancel` is invoked by `stop_children` or some other indirect mechanism. In that case, if we encounter the "current" fiber, we can't cancel it right away, as it's currently performing `#cancel`. Cancelling it immediately would interrupt the current cancel traversal, so we need to schedule the cancel to occur later.
  #
  # pkg:gem/async#lib/async/task.rb:328
  def cancel(later = T.unsafe(nil), cause: T.unsafe(nil)); end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/task.rb:423
  def cancel_deferred?; end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/task.rb:187
  def cancelled?; end

  # Alias for {#completed?}.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/task.rb:197
  def complete?; end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/task.rb:192
  def completed?; end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/task.rb:447
  def current?; end

  # Defer the handling of cancel. During the execution of the given block, if a cancel is requested, it will be deferred until the block exits. This is useful for ensuring graceful shutdown of servers and other long-running tasks. You should wrap the response handling code in a defer_cancel block to ensure that the task is cancelled when the response is complete but not before.
  #
  # You can nest calls to defer_cancel, but the cancel will only be deferred until the outermost block exits.
  #
  # If cancel is invoked a second time, it will be immediately executed.
  #
  # pkg:gem/async#lib/async/task.rb:384
  def defer_cancel; end

  # Backward compatibility alias for {#defer_cancel}.
  #
  # @deprecated Use {#defer_cancel} instead.
  #
  # pkg:gem/async#lib/async/task.rb:418
  def defer_stop(&block); end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/task.rb:182
  def failed?; end

  # Returns the value of attribute fiber.
  #
  # pkg:gem/async#lib/async/task.rb:162
  def fiber; end

  # Whether we can remove this node from the reactor graph.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/task.rb:171
  def finished?; end

  # Retrieve the current result of the task. Will cause the caller to wait until result is available. If the task resulted in an unhandled error (derived from `StandardError`), this will be raised. If the task was cancelled, this will return `nil`.
  #
  # Conceptually speaking, waiting on a task should return a result, and if it throws an exception, this is certainly an exceptional case that should represent a failure in your program, not an expected outcome. In other words, you should not design your programs to expect exceptions from `#wait` as a normal flow control, and prefer to catch known exceptions within the task itself and return a result that captures the intention of the failure, e.g. a `TimeoutError` might simply return `nil` or `false` to indicate that the operation did not generate a valid result (as a timeout was an expected outcome of the internal operation in this case).
  # For compatibility with `Thread#join` and similar interfaces.
  #
  # pkg:gem/async#lib/async/task.rb:279
  def join(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/async#lib/async/task.rb:108
  def reactor; end

  # Access the result of the task without waiting. May be nil if the task is not completed. Does not raise exceptions.
  #
  # pkg:gem/async#lib/async/task.rb:311
  def result; end

  # Begin the execution of the task.
  #
  # pkg:gem/async#lib/async/task.rb:218
  def run(*arguments); end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/task.rb:177
  def running?; end

  # @deprecated Prefer {Kernel#sleep} except when compatibility with `stable-v1` is required.
  #
  # pkg:gem/async#lib/async/task.rb:145
  def sleep(duration = T.unsafe(nil)); end

  # pkg:gem/async#lib/async/task.rb:202
  def status; end

  # Backward compatibility alias for {#cancel_deferred?}.
  #
  # @deprecated Use {#cancel_deferred?} instead.
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/task.rb:429
  def stop_deferred?; end

  # pkg:gem/async#lib/async/task.rb:140
  def to_s; end

  # Retrieve the current result of the task. Will cause the caller to wait until result is available. If the task resulted in an unhandled error (derived from `StandardError`), this will be raised. If the task was cancelled, this will return `nil`.
  #
  # Conceptually speaking, waiting on a task should return a result, and if it throws an exception, this is certainly an exceptional case that should represent a failure in your program, not an expected outcome. In other words, you should not design your programs to expect exceptions from `#wait` as a normal flow control, and prefer to catch known exceptions within the task itself and return a result that captures the intention of the failure, e.g. a `TimeoutError` might simply return `nil` or `false` to indicate that the operation did not generate a valid result (as a timeout was an expected outcome of the internal operation in this case).
  #
  # pkg:gem/async#lib/async/task.rb:271
  def wait(*_arg0, **_arg1, &_arg2); end

  # Wait on all non-transient children to complete, recursively, then wait on the task itself, if it is not the current task.
  #
  # If any child task fails with an exception, that exception will be raised immediately, and remaining children may not be waited on.
  #
  # @example Waiting on all children.
  #   Async do |task|
  #   child = task.async do
  #   sleep(0.01)
  #   end
  #   task.wait_all # Will wait on the child task.
  #   end
  #
  # pkg:gem/async#lib/async/task.rb:296
  def wait_all; end

  # Execute the given block of code, raising the specified exception if it exceeds the given duration during a non-blocking operation.
  #
  # pkg:gem/async#lib/async/task.rb:152
  def with_timeout(duration, exception = T.unsafe(nil), message = T.unsafe(nil), &block); end

  # Yield back to the reactor and allow other fibers to execute.
  #
  # pkg:gem/async#lib/async/task.rb:157
  def yield; end

  private

  # pkg:gem/async#lib/async/task.rb:505
  def cancel!; end

  # pkg:gem/async#lib/async/task.rb:479
  def cancelled!; end

  # State transition into the completed state.
  #
  # pkg:gem/async#lib/async/task.rb:468
  def completed!(result); end

  # State transition into the failed state.
  #
  # pkg:gem/async#lib/async/task.rb:474
  def failed!(exception = T.unsafe(nil)); end

  # Finish the current task, moving any children to the parent.
  #
  # pkg:gem/async#lib/async/task.rb:458
  def finish!; end

  # pkg:gem/async#lib/async/task.rb:515
  def schedule(&block); end

  # pkg:gem/async#lib/async/task.rb:511
  def stop!; end

  # pkg:gem/async#lib/async/task.rb:501
  def stopped!; end

  # pkg:gem/async#lib/async/task.rb:453
  def warn(*_arg0, **_arg1, &_arg2); end

  class << self
    # Lookup the {Task} for the current fiber. Raise `RuntimeError` if none is available.
    # @raises[RuntimeError] If task was not {set!} for the current fiber.
    #
    # pkg:gem/async#lib/async/task.rb:436
    def current; end

    # Check if there is a task defined for the current fiber.
    #
    # @return [Boolean]
    #
    # pkg:gem/async#lib/async/task.rb:442
    def current?; end

    # Run the given block of code in a task, asynchronously, in the given scheduler.
    #
    # pkg:gem/async#lib/async/task.rb:70
    def run(scheduler, *arguments, **options, &block); end

    # @deprecated With no replacement.
    #
    # pkg:gem/async#lib/async/task.rb:63
    def yield; end
  end
end

# Raised when a child task is created within a task that has finished execution.
#
# pkg:gem/async#lib/async/task.rb:53
class Async::Task::FinishedError < ::RuntimeError
  # Create a new finished error.
  #
  # @return [FinishedError] a new instance of FinishedError
  #
  # pkg:gem/async#lib/async/task.rb:57
  def initialize(message = T.unsafe(nil)); end
end

# Represents a flexible timeout that can be rescheduled or extended.
#
# pkg:gem/async#lib/async/timeout.rb:9
class Async::Timeout
  # Initialize a new timeout.
  #
  # @return [Timeout] a new instance of Timeout
  #
  # pkg:gem/async#lib/async/timeout.rb:11
  def initialize(timers, handle); end

  # Adjust the timeout by the specified duration.
  #
  # The duration is relative to the timeout time, e.g. adjusting the timeout by 5 increases the current duration by 5 seconds.
  #
  # pkg:gem/async#lib/async/timeout.rb:36
  def adjust(duration); end

  # Cancel the timeout, preventing it from executing.
  #
  # pkg:gem/async#lib/async/timeout.rb:59
  def cancel!; end

  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/timeout.rb:64
  def cancelled?; end

  # pkg:gem/async#lib/async/timeout.rb:17
  def duration; end

  # Update the duration of the timeout.
  #
  # The duration is relative to the current time, e.g. setting the duration to 5 means the timeout will occur in 5 seconds from now.
  #
  # pkg:gem/async#lib/async/timeout.rb:26
  def duration=(value); end

  # pkg:gem/async#lib/async/timeout.rb:54
  def now; end

  # pkg:gem/async#lib/async/timeout.rb:41
  def time; end

  # Assign a new time to the timeout, rescheduling it if necessary.
  #
  # pkg:gem/async#lib/async/timeout.rb:49
  def time=(value); end

  private

  # Reschedule the timeout to occur at the specified time.
  #
  # pkg:gem/async#lib/async/timeout.rb:76
  def reschedule(time); end
end

# Raised when attempting to reschedule a cancelled timeout.
#
# pkg:gem/async#lib/async/timeout.rb:69
class Async::Timeout::CancelledError < ::RuntimeError; end

# Raised if a timeout occurs on a specific Fiber. Handled gracefully by `Task`.
#
# pkg:gem/async#lib/async/error.rb:9
class Async::TimeoutError < ::StandardError
  # Create a new timeout error.
  #
  # @return [TimeoutError] a new instance of TimeoutError
  #
  # pkg:gem/async#lib/async/error.rb:13
  def initialize(message = T.unsafe(nil)); end
end

# pkg:gem/async#lib/async/version.rb:8
Async::VERSION = T.let(T.unsafe(nil), String)

# A synchronization primitive that allows one task to wait for another task to resolve a value.
#
# @deprecated Use {Async::Promise} instead.
#
# pkg:gem/async#lib/async/variable.rb:13
class Async::Variable
  # Create a new variable.
  #
  # @return [Variable] a new instance of Variable
  #
  # pkg:gem/async#lib/async/variable.rb:17
  def initialize(condition = T.unsafe(nil)); end

  # Resolve the value.
  #
  # Signals all waiting tasks.
  #
  # pkg:gem/async#lib/async/variable.rb:29
  def resolve(value = T.unsafe(nil)); end

  # Whether the value has been resolved.
  #
  # @return [Boolean]
  #
  # pkg:gem/async#lib/async/variable.rb:47
  def resolved?; end

  # Alias for {#wait}.
  #
  # pkg:gem/async#lib/async/variable.rb:60
  def value; end

  # Alias for {#resolve}.
  #
  # pkg:gem/async#lib/async/variable.rb:40
  def value=(value); end

  # Wait for the value to be resolved.
  #
  # pkg:gem/async#lib/async/variable.rb:54
  def wait; end
end

# Extensions to all Ruby objects.
#
# pkg:gem/async#lib/kernel/async.rb:8
module Kernel
  # Run the given block of code in a task, asynchronously, creating a reactor if necessary.
  #
  # The preferred method to invoke asynchronous behavior at the top level.
  #
  # - When invoked within an existing reactor task, it will run the given block
  # asynchronously. Will return the task once it has been scheduled.
  # - When invoked at the top level, will create and run a reactor, and invoke
  # the block as an asynchronous task. Will block until the reactor finishes
  # running.
  #
  # pkg:gem/async#lib/kernel/async.rb:24
  def Async(*_arg0, **_arg1, &_arg2); end

  # Create a barrier, yield it to the block, and then wait for all tasks to complete.
  #
  # If no scheduler is running, one will be created automatically for the duration of the block.
  #
  # By default, the barrier uses an `Async::Idler` to manage load, but this can be overridden by providing a different parent or `nil` to disable load management.
  #
  # pkg:gem/async#lib/kernel/barrier.rb:20
  def Barrier(parent: T.unsafe(nil), **options); end

  # Run the given block of code synchronously, but within a reactor if not already in one.
  #
  # pkg:gem/async#lib/kernel/sync.rb:20
  def Sync(annotation: T.unsafe(nil), &block); end
end
