# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `easy_translate` gem.
# Please instead update this file by running `bin/tapioca gem easy_translate`.


# pkg:gem/easy_translate#lib/easy_translate/request.rb:5
module EasyTranslate
  extend ::EasyTranslate::Threadable
  extend ::EasyTranslate::Detection
  extend ::EasyTranslate::Translation
  extend ::EasyTranslate::TranslationTarget

  class << self
    # Returns the value of attribute api_key.
    #
    # pkg:gem/easy_translate#lib/easy_translate.rb:18
    def api_key; end

    # Sets the attribute api_key
    #
    # @param value the value to set the attribute api_key to.
    #
    # pkg:gem/easy_translate#lib/easy_translate.rb:18
    def api_key=(_arg0); end
  end
end

# pkg:gem/easy_translate#lib/easy_translate/detection.rb:8
module EasyTranslate::Detection
  include ::EasyTranslate::Threadable

  # Detect language
  #
  # @param options [Hash] - Extra options to pass along with the request
  # @param texts [String, Array] - A single string or set of strings to detect for
  # @return [String, Array] The resultant language or languages
  #
  # pkg:gem/easy_translate#lib/easy_translate/detection.rb:15
  def detect(texts, options = T.unsafe(nil), http_options = T.unsafe(nil)); end

  private

  # pkg:gem/easy_translate#lib/easy_translate/detection.rb:20
  def request_detection(texts, options, http_options); end
end

# A convenience class for wrapping a detection request
#
# pkg:gem/easy_translate#lib/easy_translate/detection.rb:31
class EasyTranslate::Detection::DetectionRequest < ::EasyTranslate::Request
  # Set the texts and options
  #
  # @param options [Hash] - Options to override or pass along with the request
  # @param texts [String, Array] - The text (or texts) to translate
  # @return [DetectionRequest] a new instance of DetectionRequest
  #
  # pkg:gem/easy_translate#lib/easy_translate/detection.rb:36
  def initialize(texts, options = T.unsafe(nil), http_options = T.unsafe(nil)); end

  # The body for the request
  #
  # @return [String] the body for the request, URL escaped
  #
  # pkg:gem/easy_translate#lib/easy_translate/detection.rb:60
  def body; end

  # Whether or not this was a request for multiple texts
  #
  # @return [Boolean]
  #
  # pkg:gem/easy_translate#lib/easy_translate/detection.rb:66
  def multi?; end

  # The params for this request
  #
  # @return [Hash] the params for the request
  #
  # pkg:gem/easy_translate#lib/easy_translate/detection.rb:46
  def params; end

  # The path for the request
  #
  # @return [String] The path for the request
  #
  # pkg:gem/easy_translate#lib/easy_translate/detection.rb:54
  def path; end

  private

  # Set the texts for this request
  #
  # @param texts [String, Array] - The text or texts for this request
  #
  # pkg:gem/easy_translate#lib/easy_translate/detection.rb:74
  def texts=(texts); end
end

# pkg:gem/easy_translate#lib/easy_translate/easy_translate_exception.rb:3
class EasyTranslate::EasyTranslateException < ::StandardError; end

# pkg:gem/easy_translate#lib/easy_translate/languages.rb:3
EasyTranslate::LANGUAGES = T.let(T.unsafe(nil), Hash)

# pkg:gem/easy_translate#lib/easy_translate/request.rb:7
class EasyTranslate::Request
  # @return [Request] a new instance of Request
  #
  # pkg:gem/easy_translate#lib/easy_translate/request.rb:10
  def initialize(options = T.unsafe(nil), http_options = T.unsafe(nil)); end

  # Body, blank by default
  #
  # @return [String] The body for this request
  #
  # pkg:gem/easy_translate#lib/easy_translate/request.rb:17
  def body; end

  # Returns the value of attribute http_options.
  #
  # pkg:gem/easy_translate#lib/easy_translate/request.rb:8
  def http_options; end

  # Sets the attribute http_options
  #
  # @param value the value to set the attribute http_options to.
  #
  # pkg:gem/easy_translate#lib/easy_translate/request.rb:8
  def http_options=(_arg0); end

  # The base params for a request
  #
  # @return [Hash] a hash of the base parameters for any request
  #
  # pkg:gem/easy_translate#lib/easy_translate/request.rb:29
  def params; end

  # The path for the request
  #
  # @raise [NotImplementedError]
  # @return [String] The path for this request
  #
  # pkg:gem/easy_translate#lib/easy_translate/request.rb:23
  def path; end

  # Perform the given request
  #
  # @return [String] The response String
  #
  # pkg:gem/easy_translate#lib/easy_translate/request.rb:38
  def perform_raw; end

  private

  # pkg:gem/easy_translate#lib/easy_translate/request.rb:70
  def configure_ssl(http); end

  # pkg:gem/easy_translate#lib/easy_translate/request.rb:65
  def configure_timeouts(http); end

  # pkg:gem/easy_translate#lib/easy_translate/request.rb:58
  def http; end

  # Stringify the params
  #
  # @return [String] The params as a string
  #
  # pkg:gem/easy_translate#lib/easy_translate/request.rb:97
  def param_s; end

  # pkg:gem/easy_translate#lib/easy_translate/request.rb:83
  def ssl_cert_store; end

  # pkg:gem/easy_translate#lib/easy_translate/request.rb:91
  def ssl_options; end

  # pkg:gem/easy_translate#lib/easy_translate/request.rb:54
  def uri; end
end

# pkg:gem/easy_translate#lib/easy_translate/threadable.rb:6
module EasyTranslate::Threadable
  # pkg:gem/easy_translate#lib/easy_translate/threadable.rb:7
  def threaded_process(method, *args); end
end

# pkg:gem/easy_translate#lib/easy_translate/translation.rb:8
module EasyTranslate::Translation
  include ::EasyTranslate::Threadable

  # Translate text
  #
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @param options [Hash] a customizable set of options
  # @param texts [String, Array] - A single string or set of strings to translate
  # @return [String, Array] Translated text or texts
  #
  # pkg:gem/easy_translate#lib/easy_translate/translation.rb:19
  def translate(texts, options = T.unsafe(nil), http_options = T.unsafe(nil)); end

  private

  # Perform a single request to translate texts
  #
  # @option options
  # @option options
  # @option options
  # @param options [Hash] a customizable set of options
  # @param texts [Array] - Texts to translate
  # @return [String, Array] Translated text or texts
  #
  # pkg:gem/easy_translate#lib/easy_translate/translation.rb:31
  def request_translations(texts, options = T.unsafe(nil), http_options = T.unsafe(nil)); end
end

# A convenience class for wrapping a translation request
#
# pkg:gem/easy_translate#lib/easy_translate/translation.rb:42
class EasyTranslate::Translation::TranslationRequest < ::EasyTranslate::Request
  # Set the texts and options
  #
  # @param options [Hash] - Options to override or pass along with the request
  # @param texts [String, Array] - the text (or texts) to translate
  # @raise [ArgumentError]
  # @return [TranslationRequest] a new instance of TranslationRequest
  #
  # pkg:gem/easy_translate#lib/easy_translate/translation.rb:47
  def initialize(texts, options, http_options = T.unsafe(nil)); end

  # The body for the request
  #
  # @return [String] the body for the request, URL escaped
  #
  # pkg:gem/easy_translate#lib/easy_translate/translation.rb:85
  def body; end

  # Whether or not this was a request for multiple texts
  #
  # @return [Boolean]
  #
  # pkg:gem/easy_translate#lib/easy_translate/translation.rb:91
  def multi?; end

  # The params for this request
  #
  # @return [Hash] the params for the request
  #
  # pkg:gem/easy_translate#lib/easy_translate/translation.rb:67
  def params; end

  # The path for the request
  #
  # @return [String] The path for the request
  #
  # pkg:gem/easy_translate#lib/easy_translate/translation.rb:79
  def path; end

  private

  # Set the HTML attribute, if true add a format
  #
  # @param b [Boolean] - Whether or not the text supplied iS HTML
  #
  # pkg:gem/easy_translate#lib/easy_translate/translation.rb:109
  def html=(b); end

  # Look up a language in the table (if needed)
  #
  # pkg:gem/easy_translate#lib/easy_translate/translation.rb:98
  def lang(orig); end

  # Set the texts for this request
  #
  # @param texts [String, Array] - The text or texts for this request
  #
  # pkg:gem/easy_translate#lib/easy_translate/translation.rb:115
  def texts=(texts); end
end

# pkg:gem/easy_translate#lib/easy_translate/translation_target.rb:6
module EasyTranslate::TranslationTarget
  # Determine what translations are available
  #
  # @param options [Hash] - extra options
  # @param source [String] - The source language (optional)
  # @return [Array] an array of strings representing languages
  #
  # pkg:gem/easy_translate#lib/easy_translate/translation_target.rb:12
  def translations_available(target = T.unsafe(nil), options = T.unsafe(nil)); end
end

# pkg:gem/easy_translate#lib/easy_translate/translation_target.rb:20
class EasyTranslate::TranslationTarget::TranslationTargetRequest < ::EasyTranslate::Request
  # @return [TranslationTargetRequest] a new instance of TranslationTargetRequest
  #
  # pkg:gem/easy_translate#lib/easy_translate/translation_target.rb:22
  def initialize(target = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/easy_translate#lib/easy_translate/translation_target.rb:32
  def params; end

  # pkg:gem/easy_translate#lib/easy_translate/translation_target.rb:39
  def path; end
end

# pkg:gem/easy_translate#lib/easy_translate/version.rb:3
EasyTranslate::VERSION = T.let(T.unsafe(nil), String)
