# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faraday-em_synchrony/all/faraday-em_synchrony.rbi
#
# faraday-em_synchrony-1.0.0

module Faraday
end
class Faraday::Adapter
end
class Faraday::Adapter::EMSynchrony < Faraday::Adapter
  def call(env); end
  def call_block(block); end
  def create_request(env); end
  def execute_parallel_request(env, request, http_method); end
  def execute_single_request(env, request, http_method); end
  def self.setup_parallel_manager(_options = nil); end
  include Faraday::Adapter::EMHttp::Options
end
module Faraday::EmSynchrony
end
