# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `foreman` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

module Foreman
  class << self
    def ruby_18?; end
    def runner; end
    def windows?; end
  end
end

Foreman::VERSION = T.let(T.unsafe(nil), String)
