# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `octokit` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

module Octokit
  extend(::Octokit::Configurable)

  class << self
    def client; end
    def enterprise_admin_client; end
    def enterprise_management_console_client; end

    private

    def method_missing(method_name, *args, &block); end
    def respond_to_missing?(method_name, include_private = T.unsafe(nil)); end
  end
end

class Octokit::AbuseDetected < ::Octokit::Forbidden
end

class Octokit::AccountSuspended < ::Octokit::Forbidden
end

class Octokit::ApplicationCredentialsRequired < ::StandardError
end

class Octokit::Arguments < ::Array
  def initialize(args); end

  def options; end
end

module Octokit::Authentication
  def application_authenticated?; end
  def basic_authenticated?; end
  def bearer_authenticated?; end
  def token_authenticated?; end
  def user_authenticated?; end

  private

  def login_from_netrc; end
end

class Octokit::BadGateway < ::Octokit::ServerError
end

class Octokit::BadRequest < ::Octokit::ClientError
end

class Octokit::BillingIssue < ::Octokit::Forbidden
end

class Octokit::BranchNotProtected < ::Octokit::ClientError
end

class Octokit::Client
  include(::Octokit::Authentication)
  include(::Octokit::Configurable)
  include(::Octokit::Connection)
  include(::Octokit::Preview)
  include(::Octokit::Warnable)
  include(::Octokit::Client::ActionsSecrets)
  include(::Octokit::Client::Authorizations)
  include(::Octokit::Client::Checks)
  include(::Octokit::Client::Commits)
  include(::Octokit::Client::CommitComments)
  include(::Octokit::Client::CommitPulls)
  include(::Octokit::Client::CommitBranches)
  include(::Octokit::Client::CommunityProfile)
  include(::Octokit::Client::Contents)
  include(::Octokit::Client::Deployments)
  include(::Octokit::Client::Downloads)
  include(::Octokit::Client::Emojis)
  include(::Octokit::Client::Events)
  include(::Octokit::Client::Feeds)
  include(::Octokit::Client::Gists)
  include(::Octokit::Client::Gitignore)
  include(::Octokit::Client::Hooks)
  include(::Octokit::Client::ActionsWorkflows)
  include(::Octokit::Client::ActionsWorkflowRuns)
  include(::Octokit::Client::Apps)
  include(::Octokit::Client::Issues)
  include(::Octokit::Client::Labels)
  include(::Octokit::Client::LegacySearch)
  include(::Octokit::Client::Licenses)
  include(::Octokit::Client::Meta)
  include(::Octokit::Client::Markdown)
  include(::Octokit::Client::Marketplace)
  include(::Octokit::Client::Milestones)
  include(::Octokit::Client::Notifications)
  include(::Octokit::Client::OauthApplications)
  include(::Octokit::Client::Objects)
  include(::Octokit::Client::Organizations)
  include(::Octokit::Client::Pages)
  include(::Octokit::Client::Projects)
  include(::Octokit::Client::PubSubHubbub)
  include(::Octokit::Client::PullRequests)
  include(::Octokit::Client::RateLimit)
  include(::Octokit::Client::Reactions)
  include(::Octokit::Client::Refs)
  include(::Octokit::Client::Releases)
  include(::Octokit::Client::Repositories)
  include(::Octokit::Client::RepositoryInvitations)
  include(::Octokit::Client::Reviews)
  include(::Octokit::Client::Say)
  include(::Octokit::Client::Search)
  include(::Octokit::Client::ServiceStatus)
  include(::Octokit::Client::SourceImport)
  include(::Octokit::Client::Stats)
  include(::Octokit::Client::Statuses)
  include(::Octokit::Client::Traffic)
  include(::Octokit::Client::Users)

  def initialize(options = T.unsafe(nil)); end

  def access_token=(value); end
  def as_app(key = T.unsafe(nil), secret = T.unsafe(nil), &block); end
  def bearer_token=(value); end
  def client_id=(value); end
  def client_secret=(value); end
  def client_without_redirects(options = T.unsafe(nil)); end
  def inspect; end
  def login=(value); end
  def password=(value); end

  private

  def user_path(user, path); end
end

module Octokit::Client::ActionsSecrets
  def create_or_update_secret(repo, name, options); end
  def delete_secret(repo, name); end
  def get_public_key(repo); end
  def get_secret(repo, name); end
  def list_secrets(repo); end
end

module Octokit::Client::ActionsWorkflowRuns
  def cancel_workflow_run(repo, id, options = T.unsafe(nil)); end
  def delete_workflow_run_logs(repo, id, options = T.unsafe(nil)); end
  def list_repository_workflow_runs(repo, options = T.unsafe(nil)); end
  def list_workflow_runs(repo, workflow, options = T.unsafe(nil)); end
  def repository_workflow_runs(repo, options = T.unsafe(nil)); end
  def rerun_workflow_run(repo, id, options = T.unsafe(nil)); end
  def workflow_run(repo, id, options = T.unsafe(nil)); end
  def workflow_run_logs(repo, id, options = T.unsafe(nil)); end
  def workflow_runs(repo, workflow, options = T.unsafe(nil)); end
end

module Octokit::Client::ActionsWorkflows
  def list_workflows(repo, options = T.unsafe(nil)); end
  def workflow(repo, id, options = T.unsafe(nil)); end
  def workflow_dispatch(repo, id, ref, options = T.unsafe(nil)); end
  def workflows(repo, options = T.unsafe(nil)); end
end

module Octokit::Client::Apps
  def add_repo_to_installation(installation, repo, options = T.unsafe(nil)); end
  def add_repository_to_app_installation(installation, repo, options = T.unsafe(nil)); end
  def add_repository_to_integration_installation(installation, repo, options = T.unsafe(nil)); end
  def app(options = T.unsafe(nil)); end
  def create_app_installation_access_token(installation, options = T.unsafe(nil)); end
  def create_installation_access_token(installation, options = T.unsafe(nil)); end
  def create_integration_installation_access_token(installation, options = T.unsafe(nil)); end
  def delete_installation(installation, options = T.unsafe(nil)); end
  def find_app_installations(options = T.unsafe(nil)); end
  def find_installation_repositories_for_user(installation, options = T.unsafe(nil)); end
  def find_installations(options = T.unsafe(nil)); end
  def find_integration_installations(options = T.unsafe(nil)); end
  def find_organization_installation(organization, options = T.unsafe(nil)); end
  def find_repository_installation(repo, options = T.unsafe(nil)); end
  def find_user_installation(user, options = T.unsafe(nil)); end
  def find_user_installations(options = T.unsafe(nil)); end
  def installation(id, options = T.unsafe(nil)); end
  def list_app_installation_repositories(options = T.unsafe(nil)); end
  def list_installation_repos(options = T.unsafe(nil)); end
  def list_integration_installation_repositories(options = T.unsafe(nil)); end
  def remove_repo_from_installation(installation, repo, options = T.unsafe(nil)); end
  def remove_repository_from_app_installation(installation, repo, options = T.unsafe(nil)); end
  def remove_repository_from_integration_installation(installation, repo, options = T.unsafe(nil)); end
end

module Octokit::Client::Authorizations
  def authorization(number, options = T.unsafe(nil)); end
  def authorizations(options = T.unsafe(nil)); end
  def authorize_url(app_id = T.unsafe(nil), options = T.unsafe(nil)); end
  def create_authorization(options = T.unsafe(nil)); end
  def delete_authorization(number, options = T.unsafe(nil)); end
  def revoke_all_application_authorizations(options = T.unsafe(nil)); end
  def scopes(token = T.unsafe(nil), options = T.unsafe(nil)); end
  def update_authorization(number, options = T.unsafe(nil)); end
end

Octokit::Client::CONVENIENCE_HEADERS = T.let(T.unsafe(nil), Set)

module Octokit::Client::Checks
  def check_run(repo, id, options = T.unsafe(nil)); end
  def check_run_annotations(repo, id, options = T.unsafe(nil)); end
  def check_runs_for_check_suite(repo, id, options = T.unsafe(nil)); end
  def check_runs_for_ref(repo, ref, options = T.unsafe(nil)); end
  def check_suite(repo, id, options = T.unsafe(nil)); end
  def check_suites_for_ref(repo, ref, options = T.unsafe(nil)); end
  def create_check_run(repo, name, head_sha, options = T.unsafe(nil)); end
  def create_check_suite(repo, head_sha, options = T.unsafe(nil)); end
  def list_check_runs_for_check_suite(repo, id, options = T.unsafe(nil)); end
  def list_check_runs_for_ref(repo, ref, options = T.unsafe(nil)); end
  def list_check_suites_for_ref(repo, ref, options = T.unsafe(nil)); end
  def rerequest_check_suite(repo, id, options = T.unsafe(nil)); end
  def set_check_suite_preferences(repo, options = T.unsafe(nil)); end
  def update_check_run(repo, id, options = T.unsafe(nil)); end
end

module Octokit::Client::CommitBranches
  def commit_branches(repo, sha, options = T.unsafe(nil)); end
end

module Octokit::Client::CommitComments
  def commit_comment(repo, id, options = T.unsafe(nil)); end
  def commit_comments(repo, sha, options = T.unsafe(nil)); end
  def create_commit_comment(repo, sha, body, path = T.unsafe(nil), line = T.unsafe(nil), position = T.unsafe(nil), options = T.unsafe(nil)); end
  def delete_commit_comment(repo, id, options = T.unsafe(nil)); end
  def list_commit_comments(repo, options = T.unsafe(nil)); end
  def update_commit_comment(repo, id, body, options = T.unsafe(nil)); end
end

module Octokit::Client::CommitPulls
  def commit_pulls(repo, sha, options = T.unsafe(nil)); end
end

module Octokit::Client::Commits
  def commit(repo, sha, options = T.unsafe(nil)); end
  def commits(*args); end
  def commits_before(*args); end
  def commits_between(*args); end
  def commits_on(*args); end
  def commits_since(*args); end
  def compare(repo, start, endd, options = T.unsafe(nil)); end
  def create_commit(repo, message, tree, parents = T.unsafe(nil), options = T.unsafe(nil)); end
  def git_commit(repo, sha, options = T.unsafe(nil)); end
  def list_commits(*args); end
  def merge(repo, base, head, options = T.unsafe(nil)); end

  protected

  def iso8601(date); end
  def parse_date(date); end
end

module Octokit::Client::CommunityProfile
  def community_profile(repo, options = T.unsafe(nil)); end
end

module Octokit::Client::Contents
  def add_content(*args); end
  def add_contents(*args); end
  def archive_link(repo, options = T.unsafe(nil)); end
  def content(repo, options = T.unsafe(nil)); end
  def contents(repo, options = T.unsafe(nil)); end
  def create_content(*args); end
  def create_contents(*args); end
  def delete_content(repo, path, message, sha, options = T.unsafe(nil)); end
  def delete_contents(repo, path, message, sha, options = T.unsafe(nil)); end
  def readme(repo, options = T.unsafe(nil)); end
  def remove_content(repo, path, message, sha, options = T.unsafe(nil)); end
  def remove_contents(repo, path, message, sha, options = T.unsafe(nil)); end
  def update_content(*args); end
  def update_contents(*args); end
end

module Octokit::Client::Deployments
  def create_deployment(repo, ref, options = T.unsafe(nil)); end
  def create_deployment_status(deployment_url, state, options = T.unsafe(nil)); end
  def delete_deployment(repo, deployment_id, options = T.unsafe(nil)); end
  def deployment(repo, deployment_id, options = T.unsafe(nil)); end
  def deployment_statuses(deployment_url, options = T.unsafe(nil)); end
  def deployments(repo, options = T.unsafe(nil)); end
  def list_deployment_statuses(deployment_url, options = T.unsafe(nil)); end
  def list_deployments(repo, options = T.unsafe(nil)); end
end

module Octokit::Client::Downloads
  def delete_download(repo, id, options = T.unsafe(nil)); end
  def download(repo, id, options = T.unsafe(nil)); end
  def downloads(repo, options = T.unsafe(nil)); end
  def list_downloads(repo, options = T.unsafe(nil)); end
end

module Octokit::Client::Emojis
  def emojis(options = T.unsafe(nil)); end
end

module Octokit::Client::Events
  def issue_event(repo, number, options = T.unsafe(nil)); end
  def issue_events(repo, number, options = T.unsafe(nil)); end
  def organization_events(org, options = T.unsafe(nil)); end
  def organization_public_events(org, options = T.unsafe(nil)); end
  def public_events(options = T.unsafe(nil)); end
  def received_events(user, options = T.unsafe(nil)); end
  def received_public_events(user, options = T.unsafe(nil)); end
  def repo_issue_events(repo, options = T.unsafe(nil)); end
  def repository_events(repo, options = T.unsafe(nil)); end
  def repository_issue_events(repo, options = T.unsafe(nil)); end
  def repository_network_events(repo, options = T.unsafe(nil)); end
  def user_events(user, options = T.unsafe(nil)); end
  def user_public_events(user, options = T.unsafe(nil)); end
end

module Octokit::Client::Feeds
  def feed(name, options = T.unsafe(nil)); end
  def feeds; end
end

module Octokit::Client::Gists
  def create_gist(options = T.unsafe(nil)); end
  def create_gist_comment(gist_id, comment, options = T.unsafe(nil)); end
  def delete_gist(gist, options = T.unsafe(nil)); end
  def delete_gist_comment(gist_id, gist_comment_id, options = T.unsafe(nil)); end
  def edit_gist(gist, options = T.unsafe(nil)); end
  def fork_gist(gist, options = T.unsafe(nil)); end
  def gist(gist, options = T.unsafe(nil)); end
  def gist_comment(gist_id, gist_comment_id, options = T.unsafe(nil)); end
  def gist_comments(gist_id, options = T.unsafe(nil)); end
  def gist_commits(gist, options = T.unsafe(nil)); end
  def gist_forks(gist, options = T.unsafe(nil)); end
  def gist_starred?(gist, options = T.unsafe(nil)); end
  def gists(user = T.unsafe(nil), options = T.unsafe(nil)); end
  def list_gists(user = T.unsafe(nil), options = T.unsafe(nil)); end
  def public_gists(options = T.unsafe(nil)); end
  def star_gist(gist, options = T.unsafe(nil)); end
  def starred_gists(options = T.unsafe(nil)); end
  def unstar_gist(gist, options = T.unsafe(nil)); end
  def update_gist_comment(gist_id, gist_comment_id, comment, options = T.unsafe(nil)); end
end

module Octokit::Client::Gitignore
  def gitignore_template(template_name, options = T.unsafe(nil)); end
  def gitignore_templates(options = T.unsafe(nil)); end
end

module Octokit::Client::Hooks
  def available_hooks(options = T.unsafe(nil)); end
  def create_hook(repo, name, config, options = T.unsafe(nil)); end
  def create_org_hook(org, config, options = T.unsafe(nil)); end
  def edit_hook(repo, id, name, config, options = T.unsafe(nil)); end
  def edit_org_hook(org, id, config, options = T.unsafe(nil)); end
  def hook(repo, id, options = T.unsafe(nil)); end
  def hooks(repo, options = T.unsafe(nil)); end
  def list_org_hooks(org, options = T.unsafe(nil)); end
  def org_hook(org, id, options = T.unsafe(nil)); end
  def org_hooks(org, options = T.unsafe(nil)); end
  def parse_payload(payload_string); end
  def ping_hook(repo, id, options = T.unsafe(nil)); end
  def ping_org_hook(org, id, options = T.unsafe(nil)); end
  def remove_hook(repo, id, options = T.unsafe(nil)); end
  def remove_org_hook(org, id, options = T.unsafe(nil)); end
  def test_hook(repo, id, options = T.unsafe(nil)); end
  def update_org_hook(org, id, config, options = T.unsafe(nil)); end
end

module Octokit::Client::Issues
  def add_assignees(repo, number, assignees, options = T.unsafe(nil)); end
  def add_comment(repo, number, comment, options = T.unsafe(nil)); end
  def close_issue(repo, number, options = T.unsafe(nil)); end
  def create_issue(repo, title, body = T.unsafe(nil), options = T.unsafe(nil)); end
  def delete_comment(repo, number, options = T.unsafe(nil)); end
  def issue(repo, number, options = T.unsafe(nil)); end
  def issue_comment(repo, number, options = T.unsafe(nil)); end
  def issue_comments(repo, number, options = T.unsafe(nil)); end
  def issue_timeline(repo, number, options = T.unsafe(nil)); end
  def issues(repository = T.unsafe(nil), options = T.unsafe(nil)); end
  def issues_comments(repo, options = T.unsafe(nil)); end
  def list_assignees(repo, options = T.unsafe(nil)); end
  def list_issues(repository = T.unsafe(nil), options = T.unsafe(nil)); end
  def lock_issue(repo, number, options = T.unsafe(nil)); end
  def open_issue(repo, title, body = T.unsafe(nil), options = T.unsafe(nil)); end
  def org_issues(org, options = T.unsafe(nil)); end
  def remove_assignees(repo, number, assignees, options = T.unsafe(nil)); end
  def reopen_issue(repo, number, options = T.unsafe(nil)); end
  def unlock_issue(repo, number, options = T.unsafe(nil)); end
  def update_comment(repo, number, comment, options = T.unsafe(nil)); end
  def update_issue(repo, number, *args); end
  def user_issues(options = T.unsafe(nil)); end
end

module Octokit::Client::Labels
  def add_label(repo, label, color = T.unsafe(nil), options = T.unsafe(nil)); end
  def add_labels_to_an_issue(repo, number, labels); end
  def delete_label!(repo, label, options = T.unsafe(nil)); end
  def label(repo, name, options = T.unsafe(nil)); end
  def labels(repo, options = T.unsafe(nil)); end
  def labels_for_issue(repo, number, options = T.unsafe(nil)); end
  def labels_for_milestone(repo, number, options = T.unsafe(nil)); end
  def remove_all_labels(repo, number, options = T.unsafe(nil)); end
  def remove_label(repo, number, label, options = T.unsafe(nil)); end
  def replace_all_labels(repo, number, labels, options = T.unsafe(nil)); end
  def update_label(repo, label, options = T.unsafe(nil)); end
end

module Octokit::Client::LegacySearch
  def legacy_search_issues(repo, search_term, state = T.unsafe(nil), options = T.unsafe(nil)); end
  def legacy_search_repositories(q, options = T.unsafe(nil)); end
  def legacy_search_users(search, options = T.unsafe(nil)); end
end

module Octokit::Client::Licenses
  def license(license_name, options = T.unsafe(nil)); end
  def licenses(options = T.unsafe(nil)); end
  def repository_license_contents(repo, options = T.unsafe(nil)); end
end

module Octokit::Client::Markdown
  def markdown(text, options = T.unsafe(nil)); end
end

module Octokit::Client::Marketplace
  def list_accounts_for_plan(plan_id, options = T.unsafe(nil)); end
  def list_plans(options = T.unsafe(nil)); end
  def marketplace_purchases(options = T.unsafe(nil)); end
  def plan_for_account(account_id, options = T.unsafe(nil)); end
end

module Octokit::Client::Meta
  def github_meta(options = T.unsafe(nil)); end
  def meta(options = T.unsafe(nil)); end
end

module Octokit::Client::Milestones
  def create_milestone(repository, title, options = T.unsafe(nil)); end
  def delete_milestone(repository, number, options = T.unsafe(nil)); end
  def edit_milestone(repository, number, options = T.unsafe(nil)); end
  def list_milestones(repository, options = T.unsafe(nil)); end
  def milestone(repository, number, options = T.unsafe(nil)); end
  def milestones(repository, options = T.unsafe(nil)); end
  def update_milestone(repository, number, options = T.unsafe(nil)); end
end

module Octokit::Client::Notifications
  def delete_thread_subscription(thread_id, options = T.unsafe(nil)); end
  def mark_notifications_as_read(options = T.unsafe(nil)); end
  def mark_repo_notifications_as_read(repo, options = T.unsafe(nil)); end
  def mark_repository_notifications_as_read(repo, options = T.unsafe(nil)); end
  def mark_thread_as_read(thread_id, options = T.unsafe(nil)); end
  def notifications(options = T.unsafe(nil)); end
  def repo_notifications(repo, options = T.unsafe(nil)); end
  def repository_notifications(repo, options = T.unsafe(nil)); end
  def thread_notifications(thread_id, options = T.unsafe(nil)); end
  def thread_subscription(thread_id, options = T.unsafe(nil)); end
  def update_thread_subscription(thread_id, options = T.unsafe(nil)); end
end

module Octokit::Client::OauthApplications
  def check_application_authorization(access_token, options = T.unsafe(nil)); end
  def check_token(access_token, options = T.unsafe(nil)); end
  def delete_app_authorization(access_token, options = T.unsafe(nil)); end
  def delete_app_token(access_token, options = T.unsafe(nil)); end
  def delete_application_authorization(access_token, options = T.unsafe(nil)); end
  def reset_application_authorization(access_token, options = T.unsafe(nil)); end
  def reset_token(access_token, options = T.unsafe(nil)); end
  def revoke_application_authorization(access_token, options = T.unsafe(nil)); end
end

module Octokit::Client::Objects
  def blob(repo, blob_sha, options = T.unsafe(nil)); end
  def create_blob(repo, content, encoding = T.unsafe(nil), options = T.unsafe(nil)); end
  def create_tag(repo, tag, message, object_sha, type, tagger_name, tagger_email, tagger_date, options = T.unsafe(nil)); end
  def create_tree(repo, tree, options = T.unsafe(nil)); end
  def tag(repo, tag_sha, options = T.unsafe(nil)); end
  def tree(repo, tree_sha, options = T.unsafe(nil)); end
end

module Octokit::Client::Organizations
  def add_team_member(team_id, user, options = T.unsafe(nil)); end
  def add_team_membership(team_id, user, options = T.unsafe(nil)); end
  def add_team_repo(team_id, repo, options = T.unsafe(nil)); end
  def add_team_repository(team_id, repo, options = T.unsafe(nil)); end
  def all_organizations(options = T.unsafe(nil)); end
  def all_orgs(options = T.unsafe(nil)); end
  def child_teams(team_id, options = T.unsafe(nil)); end
  def conceal_membership(org, user, options = T.unsafe(nil)); end
  def convert_to_outside_collaborator(org, user, options = T.unsafe(nil)); end
  def create_team(org, options = T.unsafe(nil)); end
  def delete_migration_archive(org, id, options = T.unsafe(nil)); end
  def delete_team(team_id, options = T.unsafe(nil)); end
  def list_organizations(user = T.unsafe(nil), options = T.unsafe(nil)); end
  def list_orgs(user = T.unsafe(nil), options = T.unsafe(nil)); end
  def migration_archive_url(org, id, options = T.unsafe(nil)); end
  def migration_status(org, id, options = T.unsafe(nil)); end
  def migrations(org, options = T.unsafe(nil)); end
  def org(org, options = T.unsafe(nil)); end
  def org_invitations(org, options = T.unsafe(nil)); end
  def org_member?(org, user, options = T.unsafe(nil)); end
  def org_members(org, options = T.unsafe(nil)); end
  def org_membership(org, options = T.unsafe(nil)); end
  def org_memberships(options = T.unsafe(nil)); end
  def org_public_member?(org, user, options = T.unsafe(nil)); end
  def org_public_members(org, options = T.unsafe(nil)); end
  def org_repos(org, options = T.unsafe(nil)); end
  def org_repositories(org, options = T.unsafe(nil)); end
  def org_teams(org, options = T.unsafe(nil)); end
  def organization(org, options = T.unsafe(nil)); end
  def organization_invitations(org, options = T.unsafe(nil)); end
  def organization_member?(org, user, options = T.unsafe(nil)); end
  def organization_members(org, options = T.unsafe(nil)); end
  def organization_membership(org, options = T.unsafe(nil)); end
  def organization_memberships(options = T.unsafe(nil)); end
  def organization_public_member?(org, user, options = T.unsafe(nil)); end
  def organization_public_members(org, options = T.unsafe(nil)); end
  def organization_repositories(org, options = T.unsafe(nil)); end
  def organization_teams(org, options = T.unsafe(nil)); end
  def organizations(user = T.unsafe(nil), options = T.unsafe(nil)); end
  def orgs(user = T.unsafe(nil), options = T.unsafe(nil)); end
  def outside_collaborators(org, options = T.unsafe(nil)); end
  def publicize_membership(org, user, options = T.unsafe(nil)); end
  def remove_org_member(org, user, options = T.unsafe(nil)); end
  def remove_org_membership(org, options = T.unsafe(nil)); end
  def remove_organization_member(org, user, options = T.unsafe(nil)); end
  def remove_organization_membership(org, options = T.unsafe(nil)); end
  def remove_outside_collaborator(org, user, options = T.unsafe(nil)); end
  def remove_team_member(team_id, user, options = T.unsafe(nil)); end
  def remove_team_membership(team_id, user, options = T.unsafe(nil)); end
  def remove_team_repo(team_id, repo, options = T.unsafe(nil)); end
  def remove_team_repository(team_id, repo, options = T.unsafe(nil)); end
  def start_migration(org, repositories, options = T.unsafe(nil)); end
  def team(team_id, options = T.unsafe(nil)); end
  def team_by_name(org, team_slug, options = T.unsafe(nil)); end
  def team_invitations(team_id, options = T.unsafe(nil)); end
  def team_member?(team_id, user, options = T.unsafe(nil)); end
  def team_members(team_id, options = T.unsafe(nil)); end
  def team_membership(team_id, user, options = T.unsafe(nil)); end
  def team_repo?(team_id, repo, options = T.unsafe(nil)); end
  def team_repos(team_id, options = T.unsafe(nil)); end
  def team_repositories(team_id, options = T.unsafe(nil)); end
  def team_repository?(team_id, repo, options = T.unsafe(nil)); end
  def unlock_repository(org, id, repo, options = T.unsafe(nil)); end
  def unpublicize_membership(org, user, options = T.unsafe(nil)); end
  def update_org(org, values, options = T.unsafe(nil)); end
  def update_org_membership(org, options = T.unsafe(nil)); end
  def update_organization(org, values, options = T.unsafe(nil)); end
  def update_organization_membership(org, options = T.unsafe(nil)); end
  def update_team(team_id, options = T.unsafe(nil)); end
  def user_teams(options = T.unsafe(nil)); end
end

module Octokit::Client::Pages
  def latest_pages_build(repo, options = T.unsafe(nil)); end
  def list_pages_builds(repo, options = T.unsafe(nil)); end
  def pages(repo, options = T.unsafe(nil)); end
  def pages_build(repo, id, options = T.unsafe(nil)); end
  def pages_builds(repo, options = T.unsafe(nil)); end
  def request_page_build(repo, options = T.unsafe(nil)); end
end

module Octokit::Client::Projects
  def column_cards(id, options = T.unsafe(nil)); end
  def create_org_project(org, name, options = T.unsafe(nil)); end
  def create_organization_project(org, name, options = T.unsafe(nil)); end
  def create_project(repo, name, options = T.unsafe(nil)); end
  def create_project_card(id, options = T.unsafe(nil)); end
  def create_project_column(id, name, options = T.unsafe(nil)); end
  def delete_project(id, options = T.unsafe(nil)); end
  def delete_project_card(id, options = T.unsafe(nil)); end
  def delete_project_column(id, options = T.unsafe(nil)); end
  def move_project_card(id, position, options = T.unsafe(nil)); end
  def move_project_column(id, position, options = T.unsafe(nil)); end
  def org_projects(org, options = T.unsafe(nil)); end
  def organization_projects(org, options = T.unsafe(nil)); end
  def project(id, options = T.unsafe(nil)); end
  def project_card(id, options = T.unsafe(nil)); end
  def project_column(id, options = T.unsafe(nil)); end
  def project_columns(id, options = T.unsafe(nil)); end
  def projects(repo, options = T.unsafe(nil)); end
  def update_project(id, options = T.unsafe(nil)); end
  def update_project_card(id, options = T.unsafe(nil)); end
  def update_project_column(id, name, options = T.unsafe(nil)); end
end

module Octokit::Client::PubSubHubbub
  def subscribe(topic, callback, secret = T.unsafe(nil)); end
  def subscribe_service_hook(repo, service_name, service_arguments = T.unsafe(nil), secret = T.unsafe(nil)); end
  def unsubscribe(topic, callback); end
  def unsubscribe_service_hook(repo, service_name); end

  private

  def pub_sub_hubbub_request(options = T.unsafe(nil)); end
end

module Octokit::Client::PullRequests
  def close_pull_request(repo, number, options = T.unsafe(nil)); end
  def create_pull_comment(repo, pull_id, body, commit_id, path, position, options = T.unsafe(nil)); end
  def create_pull_reply(repo, pull_id, body, comment_id, options = T.unsafe(nil)); end
  def create_pull_request(repo, base, head, title, body = T.unsafe(nil), options = T.unsafe(nil)); end
  def create_pull_request_comment(repo, pull_id, body, commit_id, path, position, options = T.unsafe(nil)); end
  def create_pull_request_comment_reply(repo, pull_id, body, comment_id, options = T.unsafe(nil)); end
  def create_pull_request_for_issue(repo, base, head, issue, options = T.unsafe(nil)); end
  def create_review_reply(repo, pull_id, body, comment_id, options = T.unsafe(nil)); end
  def create_view_comment(repo, pull_id, body, commit_id, path, position, options = T.unsafe(nil)); end
  def delete_pull_comment(repo, comment_id, options = T.unsafe(nil)); end
  def delete_pull_request_comment(repo, comment_id, options = T.unsafe(nil)); end
  def delete_review_comment(repo, comment_id, options = T.unsafe(nil)); end
  def merge_pull_request(repo, number, commit_message = T.unsafe(nil), options = T.unsafe(nil)); end
  def pull(repo, number, options = T.unsafe(nil)); end
  def pull_comment(repo, comment_id, options = T.unsafe(nil)); end
  def pull_comments(repo, number, options = T.unsafe(nil)); end
  def pull_commits(repo, number, options = T.unsafe(nil)); end
  def pull_files(repo, number, options = T.unsafe(nil)); end
  def pull_merged?(repo, number, options = T.unsafe(nil)); end
  def pull_request(repo, number, options = T.unsafe(nil)); end
  def pull_request_comment(repo, comment_id, options = T.unsafe(nil)); end
  def pull_request_comments(repo, number, options = T.unsafe(nil)); end
  def pull_request_commits(repo, number, options = T.unsafe(nil)); end
  def pull_request_files(repo, number, options = T.unsafe(nil)); end
  def pull_request_merged?(repo, number, options = T.unsafe(nil)); end
  def pull_requests(repo, options = T.unsafe(nil)); end
  def pull_requests_comments(repo, options = T.unsafe(nil)); end
  def pulls(repo, options = T.unsafe(nil)); end
  def pulls_comments(repo, options = T.unsafe(nil)); end
  def review_comment(repo, comment_id, options = T.unsafe(nil)); end
  def review_comments(repo, number, options = T.unsafe(nil)); end
  def reviews_comments(repo, options = T.unsafe(nil)); end
  def update_pull_comment(repo, comment_id, body, options = T.unsafe(nil)); end
  def update_pull_request(*args); end
  def update_pull_request_comment(repo, comment_id, body, options = T.unsafe(nil)); end
  def update_review_comment(repo, comment_id, body, options = T.unsafe(nil)); end
end

module Octokit::Client::RateLimit
  def rate_limit(options = T.unsafe(nil)); end
  def rate_limit!(options = T.unsafe(nil)); end
  def rate_limit_remaining(options = T.unsafe(nil)); end
  def rate_limit_remaining!(options = T.unsafe(nil)); end
  def ratelimit(options = T.unsafe(nil)); end
  def ratelimit!(options = T.unsafe(nil)); end
  def ratelimit_remaining(options = T.unsafe(nil)); end
  def ratelimit_remaining!(options = T.unsafe(nil)); end
end

module Octokit::Client::Reactions
  def commit_comment_reactions(repo, id, options = T.unsafe(nil)); end
  def create_commit_comment_reaction(repo, id, reaction, options = T.unsafe(nil)); end
  def create_issue_comment_reaction(repo, id, reaction, options = T.unsafe(nil)); end
  def create_issue_reaction(repo, number, reaction, options = T.unsafe(nil)); end
  def create_pull_request_review_comment_reaction(repo, id, reaction, options = T.unsafe(nil)); end
  def delete_reaction(id, options = T.unsafe(nil)); end
  def issue_comment_reactions(repo, id, options = T.unsafe(nil)); end
  def issue_reactions(repo, number, options = T.unsafe(nil)); end
  def pull_request_review_comment_reactions(repo, id, options = T.unsafe(nil)); end
end

module Octokit::Client::Refs
  def create_ref(repo, ref, sha, options = T.unsafe(nil)); end
  def create_reference(repo, ref, sha, options = T.unsafe(nil)); end
  def delete_branch(repo, branch, options = T.unsafe(nil)); end
  def delete_ref(repo, ref, options = T.unsafe(nil)); end
  def delete_reference(repo, ref, options = T.unsafe(nil)); end
  def list_references(repo, namespace = T.unsafe(nil), options = T.unsafe(nil)); end
  def list_refs(repo, namespace = T.unsafe(nil), options = T.unsafe(nil)); end
  def ref(repo, ref, options = T.unsafe(nil)); end
  def reference(repo, ref, options = T.unsafe(nil)); end
  def references(repo, namespace = T.unsafe(nil), options = T.unsafe(nil)); end
  def refs(repo, namespace = T.unsafe(nil), options = T.unsafe(nil)); end
  def update_branch(repo, branch, sha, force = T.unsafe(nil), options = T.unsafe(nil)); end
  def update_ref(repo, ref, sha, force = T.unsafe(nil), options = T.unsafe(nil)); end
  def update_reference(repo, ref, sha, force = T.unsafe(nil), options = T.unsafe(nil)); end
end

module Octokit::Client::Releases
  def create_release(repo, tag_name, options = T.unsafe(nil)); end
  def delete_release(url, options = T.unsafe(nil)); end
  def delete_release_asset(asset_url, options = T.unsafe(nil)); end
  def edit_release(url, options = T.unsafe(nil)); end
  def edit_release_asset(asset_url, options = T.unsafe(nil)); end
  def latest_release(repo, options = T.unsafe(nil)); end
  def list_releases(repo, options = T.unsafe(nil)); end
  def release(url, options = T.unsafe(nil)); end
  def release_asset(asset_url, options = T.unsafe(nil)); end
  def release_assets(release_url, options = T.unsafe(nil)); end
  def release_for_tag(repo, tag_name, options = T.unsafe(nil)); end
  def releases(repo, options = T.unsafe(nil)); end
  def update_release(url, options = T.unsafe(nil)); end
  def update_release_asset(asset_url, options = T.unsafe(nil)); end
  def upload_asset(release_url, path_or_file, options = T.unsafe(nil)); end

  private

  def content_type_from_file(file); end
end

module Octokit::Client::Repositories
  def add_collab(repo, collaborator, options = T.unsafe(nil)); end
  def add_collaborator(repo, collaborator, options = T.unsafe(nil)); end
  def add_deploy_key(repo, title, key, options = T.unsafe(nil)); end
  def all_repositories(options = T.unsafe(nil)); end
  def branch(repo, branch, options = T.unsafe(nil)); end
  def branch_protection(repo, branch, options = T.unsafe(nil)); end
  def branches(repo, options = T.unsafe(nil)); end
  def check_assignee(repo, assignee, options = T.unsafe(nil)); end
  def collaborator?(repo, collaborator, options = T.unsafe(nil)); end
  def collaborators(repo, options = T.unsafe(nil)); end
  def collabs(repo, options = T.unsafe(nil)); end
  def contribs(repo, anon = T.unsafe(nil), options = T.unsafe(nil)); end
  def contributors(repo, anon = T.unsafe(nil), options = T.unsafe(nil)); end
  def create(name, options = T.unsafe(nil)); end
  def create_repo(name, options = T.unsafe(nil)); end
  def create_repo_from_template(repo, name, options = T.unsafe(nil)); end
  def create_repository(name, options = T.unsafe(nil)); end
  def create_repository_from_template(repo, name, options = T.unsafe(nil)); end
  def delete_repo(repo, options = T.unsafe(nil)); end
  def delete_repository(repo, options = T.unsafe(nil)); end
  def delete_subscription(repo, options = T.unsafe(nil)); end
  def deploy_key(repo, id, options = T.unsafe(nil)); end
  def deploy_keys(repo, options = T.unsafe(nil)); end
  def disable_vulnerability_alerts(repo, options = T.unsafe(nil)); end
  def dispatch_event(repo, event_type, options = T.unsafe(nil)); end
  def edit(repo, options = T.unsafe(nil)); end
  def edit_deploy_key(repo, id, options); end
  def edit_repository(repo, options = T.unsafe(nil)); end
  def enable_vulnerability_alerts(repo, options = T.unsafe(nil)); end
  def fork(repo, options = T.unsafe(nil)); end
  def forks(repo, options = T.unsafe(nil)); end
  def get_branch(repo, branch, options = T.unsafe(nil)); end
  def languages(repo, options = T.unsafe(nil)); end
  def list_deploy_keys(repo, options = T.unsafe(nil)); end
  def list_repos(user = T.unsafe(nil), options = T.unsafe(nil)); end
  def list_repositories(user = T.unsafe(nil), options = T.unsafe(nil)); end
  def network(repo, options = T.unsafe(nil)); end
  def permission_level(repo, collaborator, options = T.unsafe(nil)); end
  def protect_branch(repo, branch, options = T.unsafe(nil)); end
  def remove_collab(repo, collaborator, options = T.unsafe(nil)); end
  def remove_collaborator(repo, collaborator, options = T.unsafe(nil)); end
  def remove_deploy_key(repo, id, options = T.unsafe(nil)); end
  def replace_all_topics(repo, names, options = T.unsafe(nil)); end
  def repo(repo, options = T.unsafe(nil)); end
  def repo_assignees(repo, options = T.unsafe(nil)); end
  def repo_teams(repo, options = T.unsafe(nil)); end
  def repos(user = T.unsafe(nil), options = T.unsafe(nil)); end
  def repositories(user = T.unsafe(nil), options = T.unsafe(nil)); end
  def repository(repo, options = T.unsafe(nil)); end
  def repository?(repo, options = T.unsafe(nil)); end
  def repository_assignees(repo, options = T.unsafe(nil)); end
  def repository_teams(repo, options = T.unsafe(nil)); end
  def set_private(repo, options = T.unsafe(nil)); end
  def set_public(repo, options = T.unsafe(nil)); end
  def star(repo, options = T.unsafe(nil)); end
  def stargazers(repo, options = T.unsafe(nil)); end
  def subscribers(repo, options = T.unsafe(nil)); end
  def subscription(repo, options = T.unsafe(nil)); end
  def tags(repo, options = T.unsafe(nil)); end
  def teams(repo, options = T.unsafe(nil)); end
  def topics(repo, options = T.unsafe(nil)); end
  def transfer_repo(repo, new_owner, options = T.unsafe(nil)); end
  def transfer_repository(repo, new_owner, options = T.unsafe(nil)); end
  def unprotect_branch(repo, branch, options = T.unsafe(nil)); end
  def unstar(repo, options = T.unsafe(nil)); end
  def unwatch(repo, options = T.unsafe(nil)); end
  def update(repo, options = T.unsafe(nil)); end
  def update_deploy_key(repo, id, options); end
  def update_repository(repo, options = T.unsafe(nil)); end
  def update_subscription(repo, options = T.unsafe(nil)); end
  def vulnerability_alerts_enabled?(repo, options = T.unsafe(nil)); end
  def watch(repo, options = T.unsafe(nil)); end
  def watchers(repo, options = T.unsafe(nil)); end
end

module Octokit::Client::RepositoryInvitations
  def accept_repo_invitation(invitation_id, options = T.unsafe(nil)); end
  def accept_repository_invitation(invitation_id, options = T.unsafe(nil)); end
  def decline_invitation(invitation_id, options = T.unsafe(nil)); end
  def decline_repository_invitation(invitation_id, options = T.unsafe(nil)); end
  def delete_repo_invitation(repo, invitation_id, options = T.unsafe(nil)); end
  def delete_repository_invitation(repo, invitation_id, options = T.unsafe(nil)); end
  def invite_user_to_repo(repo, user, options = T.unsafe(nil)); end
  def invite_user_to_repository(repo, user, options = T.unsafe(nil)); end
  def repo_invitations(repo, options = T.unsafe(nil)); end
  def repository_invitations(repo, options = T.unsafe(nil)); end
  def update_repo_invitation(repo, invitation_id, options = T.unsafe(nil)); end
  def update_repository_invitation(repo, invitation_id, options = T.unsafe(nil)); end
  def user_repo_invitations(options = T.unsafe(nil)); end
  def user_repository_invitations(options = T.unsafe(nil)); end
end

module Octokit::Client::Reviews
  def create_pull_request_review(repo, number, options = T.unsafe(nil)); end
  def delete_pull_request_review(repo, number, review, options = T.unsafe(nil)); end
  def delete_pull_request_review_request(repo, id, reviewers = T.unsafe(nil), options = T.unsafe(nil)); end
  def dismiss_pull_request_review(repo, number, review, message, options = T.unsafe(nil)); end
  def pull_request_review(repo, number, review, options = T.unsafe(nil)); end
  def pull_request_review_comments(repo, number, review, options = T.unsafe(nil)); end
  def pull_request_review_requests(repo, number, options = T.unsafe(nil)); end
  def pull_request_reviews(repo, number, options = T.unsafe(nil)); end
  def request_pull_request_review(repo, number, reviewers = T.unsafe(nil), options = T.unsafe(nil)); end
  def submit_pull_request_review(repo, number, review, event, options = T.unsafe(nil)); end
  def update_pull_request_review(repo, number, review, body, options = T.unsafe(nil)); end
end

module Octokit::Client::Say
  def octocat(text = T.unsafe(nil), options = T.unsafe(nil)); end
  def say(text = T.unsafe(nil), options = T.unsafe(nil)); end
end

module Octokit::Client::Search
  def search_code(query, options = T.unsafe(nil)); end
  def search_commits(query, options = T.unsafe(nil)); end
  def search_issues(query, options = T.unsafe(nil)); end
  def search_repos(query, options = T.unsafe(nil)); end
  def search_repositories(query, options = T.unsafe(nil)); end
  def search_users(query, options = T.unsafe(nil)); end

  private

  def search(path, query, options = T.unsafe(nil)); end
end

module Octokit::Client::ServiceStatus
  def github_status; end
  def github_status_last_message; end
  def github_status_messages; end
end

Octokit::Client::ServiceStatus::STATUS_ROOT = T.let(T.unsafe(nil), String)

module Octokit::Client::SourceImport
  def cancel_source_import(repo, options = T.unsafe(nil)); end
  def map_source_import_commit_author(author_url, values, options = T.unsafe(nil)); end
  def set_source_import_lfs_preference(repo, use_lfs, options = T.unsafe(nil)); end
  def source_import_commit_authors(repo, options = T.unsafe(nil)); end
  def source_import_large_files(repo, options = T.unsafe(nil)); end
  def source_import_progress(repo, options = T.unsafe(nil)); end
  def start_source_import(*args); end
  def update_source_import(repo, options = T.unsafe(nil)); end
end

module Octokit::Client::Stats
  def code_frequency_stats(repo, options = T.unsafe(nil)); end
  def commit_activity_stats(repo, options = T.unsafe(nil)); end
  def contributor_stats(repo, options = T.unsafe(nil)); end
  def contributors_stats(repo, options = T.unsafe(nil)); end
  def participation_stats(repo, options = T.unsafe(nil)); end
  def punch_card(repo, options = T.unsafe(nil)); end
  def punch_card_stats(repo, options = T.unsafe(nil)); end

  private

  def get_stats(repo, metric, options = T.unsafe(nil)); end
end

module Octokit::Client::Statuses
  def combined_status(repo, ref, options = T.unsafe(nil)); end
  def create_status(repo, sha, state, options = T.unsafe(nil)); end
  def list_statuses(repo, sha, options = T.unsafe(nil)); end
  def status(repo, ref, options = T.unsafe(nil)); end
  def statuses(repo, sha, options = T.unsafe(nil)); end
end

module Octokit::Client::Traffic
  def clones(repo, options = T.unsafe(nil)); end
  def top_paths(repo, options = T.unsafe(nil)); end
  def top_referrers(repo, options = T.unsafe(nil)); end
  def views(repo, options = T.unsafe(nil)); end
end

module Octokit::Client::Users
  def add_email(email, options = T.unsafe(nil)); end
  def add_key(title, key, options = T.unsafe(nil)); end
  def all_users(options = T.unsafe(nil)); end
  def delete_user_migration_archive(id, options = T.unsafe(nil)); end
  def emails(options = T.unsafe(nil)); end
  def exchange_code_for_token(code, app_id = T.unsafe(nil), app_secret = T.unsafe(nil), options = T.unsafe(nil)); end
  def follow(user, options = T.unsafe(nil)); end
  def followers(user = T.unsafe(nil), options = T.unsafe(nil)); end
  def following(user = T.unsafe(nil), options = T.unsafe(nil)); end
  def follows?(*args); end
  def key(key_id, options = T.unsafe(nil)); end
  def keys(options = T.unsafe(nil)); end
  def remove_email(email); end
  def remove_key(id, options = T.unsafe(nil)); end
  def starred(user = T.unsafe(nil), options = T.unsafe(nil)); end
  def starred?(repo, options = T.unsafe(nil)); end
  def start_user_migration(repositories, options = T.unsafe(nil)); end
  def subscriptions(user = T.unsafe(nil), options = T.unsafe(nil)); end
  def unfollow(user, options = T.unsafe(nil)); end
  def unlock_user_repository(id, repo, options = T.unsafe(nil)); end
  def update_key(key_id, options = T.unsafe(nil)); end
  def update_user(options); end
  def user(user = T.unsafe(nil), options = T.unsafe(nil)); end
  def user_keys(user, options = T.unsafe(nil)); end
  def user_migration_archive_url(id, options = T.unsafe(nil)); end
  def user_migration_repositories(id, options = T.unsafe(nil)); end
  def user_migration_status(id, options = T.unsafe(nil)); end
  def user_migrations(options = T.unsafe(nil)); end
  def validate_credentials(options = T.unsafe(nil)); end
  def watched(user = T.unsafe(nil), options = T.unsafe(nil)); end
end

class Octokit::ClientError < ::Octokit::Error
end

class Octokit::CommitIsNotPartOfPullRequest < ::Octokit::UnprocessableEntity
end

module Octokit::Configurable
  def access_token; end
  def access_token=(_arg0); end
  def api_endpoint; end
  def api_endpoint=(_arg0); end
  def auto_paginate; end
  def auto_paginate=(_arg0); end
  def bearer_token; end
  def bearer_token=(_arg0); end
  def client_id; end
  def client_id=(_arg0); end
  def client_secret; end
  def client_secret=(_arg0); end
  def configure; end
  def connection_options; end
  def connection_options=(_arg0); end
  def default_media_type; end
  def default_media_type=(_arg0); end
  def login; end
  def login=(_arg0); end
  def management_console_endpoint; end
  def management_console_endpoint=(_arg0); end
  def management_console_password=(_arg0); end
  def middleware; end
  def middleware=(_arg0); end
  def netrc; end
  def netrc=(_arg0); end
  def netrc?; end
  def netrc_file; end
  def netrc_file=(_arg0); end
  def password=(_arg0); end
  def per_page; end
  def per_page=(_arg0); end
  def proxy; end
  def proxy=(_arg0); end
  def reset!; end
  def same_options?(opts); end
  def setup; end
  def ssl_verify_mode; end
  def ssl_verify_mode=(_arg0); end
  def user_agent; end
  def user_agent=(_arg0); end
  def web_endpoint; end
  def web_endpoint=(_arg0); end

  private

  def fetch_client_id_and_secret(overrides = T.unsafe(nil)); end
  def options; end

  class << self
    def keys; end
  end
end

class Octokit::Conflict < ::Octokit::ClientError
end

module Octokit::Connection
  include(::Octokit::Authentication)

  def agent; end
  def delete(url, options = T.unsafe(nil)); end
  def get(url, options = T.unsafe(nil)); end
  def head(url, options = T.unsafe(nil)); end
  def last_response; end
  def paginate(url, options = T.unsafe(nil), &block); end
  def patch(url, options = T.unsafe(nil)); end
  def post(url, options = T.unsafe(nil)); end
  def put(url, options = T.unsafe(nil)); end
  def root; end

  protected

  def endpoint; end

  private

  def boolean_from_response(method, path, options = T.unsafe(nil)); end
  def parse_query_and_convenience_headers(options); end
  def request(method, path, data, options = T.unsafe(nil)); end
  def reset_agent; end
  def sawyer_options; end
end

Octokit::Connection::CONVENIENCE_HEADERS = T.let(T.unsafe(nil), Set)

module Octokit::Default
  class << self
    def access_token; end
    def api_endpoint; end
    def auto_paginate; end
    def bearer_token; end
    def client_id; end
    def client_secret; end
    def connection_options; end
    def default_media_type; end
    def login; end
    def management_console_endpoint; end
    def management_console_password; end
    def middleware; end
    def netrc; end
    def netrc_file; end
    def options; end
    def password; end
    def per_page; end
    def proxy; end
    def ssl_verify_mode; end
    def user_agent; end
    def web_endpoint; end
  end
end

Octokit::Default::API_ENDPOINT = T.let(T.unsafe(nil), String)

Octokit::Default::MEDIA_TYPE = T.let(T.unsafe(nil), String)

Octokit::Default::MIDDLEWARE = T.let(T.unsafe(nil), Faraday::RackBuilder)

Octokit::Default::RACK_BUILDER_CLASS = Faraday::RackBuilder

Octokit::Default::USER_AGENT = T.let(T.unsafe(nil), String)

Octokit::Default::WEB_ENDPOINT = T.let(T.unsafe(nil), String)

class Octokit::EnterpriseAdminClient
  include(::Octokit::Configurable)
  include(::Octokit::Authentication)
  include(::Octokit::Connection)
  include(::Octokit::Warnable)
  include(::Octokit::EnterpriseAdminClient::AdminStats)
  include(::Octokit::EnterpriseAdminClient::License)
  include(::Octokit::EnterpriseAdminClient::Orgs)
  include(::Octokit::EnterpriseAdminClient::SearchIndexing)
  include(::Octokit::EnterpriseAdminClient::Users)

  def initialize(options = T.unsafe(nil)); end
end

module Octokit::EnterpriseAdminClient::AdminStats
  def admin_comments_stats; end
  def admin_gists_stats; end
  def admin_hooks_stats; end
  def admin_issues_stats; end
  def admin_milestones_stats; end
  def admin_organization_stats; end
  def admin_pages_stats; end
  def admin_pull_requests_stats; end
  def admin_repository_stats; end
  def admin_stats; end
  def admin_users_stats; end

  private

  def get_admin_stats(metric); end
end

module Octokit::EnterpriseAdminClient::License
  def license_info; end
end

module Octokit::EnterpriseAdminClient::Orgs
  def create_organization(login, admin, options = T.unsafe(nil)); end
end

module Octokit::EnterpriseAdminClient::SearchIndexing
  def index_organization(user); end
  def index_organizations_repositories(user); end
  def index_organizations_repositories_code(user); end
  def index_organizations_repositories_issues(user); end
  def index_repository(repo); end
  def index_repository_code(repo); end
  def index_repository_issues(repo); end
  def index_user(user); end
  def index_users_repositories(user); end
  def index_users_repositories_code(user); end
  def index_users_repositories_issues(user); end

  private

  def queue_index(target); end
end

module Octokit::EnterpriseAdminClient::Users
  def create_impersonation_token(login, options = T.unsafe(nil)); end
  def create_user(login, email, options = T.unsafe(nil)); end
  def delete_impersonation_token(login, options = T.unsafe(nil)); end
  def delete_key(id, options = T.unsafe(nil)); end
  def delete_user(username, options = T.unsafe(nil)); end
  def demote(user, options = T.unsafe(nil)); end
  def list_all_keys(options = T.unsafe(nil)); end
  def promote(user, options = T.unsafe(nil)); end
  def rename_user(old_login, new_login, options = T.unsafe(nil)); end
  def suspend(user, options = T.unsafe(nil)); end
  def unsuspend(user, options = T.unsafe(nil)); end
end

class Octokit::EnterpriseManagementConsoleClient
  include(::Octokit::Configurable)
  include(::Octokit::Authentication)
  include(::Octokit::Connection)
  include(::Octokit::Warnable)
  include(::Octokit::EnterpriseManagementConsoleClient::ManagementConsole)

  def initialize(options = T.unsafe(nil)); end


  protected

  def endpoint; end
  def management_console_endpoint=(value); end
  def management_console_password=(value); end

  private

  def faraday_configuration; end
  def password_hash; end
end

module Octokit::EnterpriseManagementConsoleClient::ManagementConsole
  def add_authorized_key(key); end
  def authorized_keys; end
  def config_check; end
  def config_status; end
  def delete_authorized_key(key); end
  def edit_maintenance_status(maintenance); end
  def edit_settings(settings); end
  def get_authorized_keys; end
  def get_maintenance_status; end
  def get_settings; end
  def maintenance_status; end
  def remove_authorized_key(key); end
  def set_maintenance_status(maintenance); end
  def settings; end
  def start_configuration; end
  def upgrade(license); end
  def upload_license(license, settings = T.unsafe(nil)); end
end

class Octokit::Error < ::StandardError
  def initialize(response = T.unsafe(nil)); end

  def build_error_context; end
  def context; end
  def documentation_url; end
  def errors; end
  def response_body; end
  def response_headers; end
  def response_status; end

  private

  def build_error_message; end
  def data; end
  def redact_url(url_string); end
  def response_error; end
  def response_error_summary; end
  def response_message; end

  class << self
    def error_for_401(headers); end
    def error_for_403(body); end
    def error_for_404(body); end
    def error_for_422(body); end
    def from_response(response); end
  end
end

class Octokit::Forbidden < ::Octokit::ClientError
end

class Octokit::Gist
  def initialize(gist); end

  def id; end
  def id=(_arg0); end
  def to_s; end
  def url; end

  class << self
    def from_url(url); end
  end
end

class Octokit::InstallationSuspended < ::Octokit::Forbidden
end

class Octokit::InternalServerError < ::Octokit::ServerError
end

class Octokit::InvalidRepository < ::ArgumentError
end

Octokit::MAJOR = T.let(T.unsafe(nil), Integer)

Octokit::MINOR = T.let(T.unsafe(nil), Integer)

class Octokit::MethodNotAllowed < ::Octokit::ClientError
end

module Octokit::Middleware
end

class Octokit::Middleware::FollowRedirects < ::Faraday::Middleware
  def initialize(app, options = T.unsafe(nil)); end

  def call(env); end

  private

  def convert_to_get?(response); end
  def follow_limit; end
  def follow_redirect?(env, response); end
  def perform_with_redirection(env, follows); end
  def safe_escape(uri); end
  def same_host?(original_url, redirect_url); end
  def update_env(env, request_body, response); end
end

Octokit::Middleware::FollowRedirects::ALLOWED_METHODS = T.let(T.unsafe(nil), Set)

Octokit::Middleware::FollowRedirects::ENV_TO_CLEAR = T.let(T.unsafe(nil), Set)

Octokit::Middleware::FollowRedirects::FOLLOW_LIMIT = T.let(T.unsafe(nil), Integer)

Octokit::Middleware::FollowRedirects::REDIRECT_CODES = T.let(T.unsafe(nil), Set)

Octokit::Middleware::FollowRedirects::URI_UNSAFE = T.let(T.unsafe(nil), Regexp)

class Octokit::Middleware::RedirectLimitReached < ::Faraday::ClientError
  def initialize(response); end

  def response; end
end

class Octokit::MissingContentType < ::ArgumentError
end

class Octokit::NotAcceptable < ::Octokit::ClientError
end

class Octokit::NotFound < ::Octokit::ClientError
end

class Octokit::NotImplemented < ::Octokit::ServerError
end

class Octokit::OneTimePasswordRequired < ::Octokit::ClientError
  def password_delivery; end

  private

  def delivery_method_from_header; end

  class << self
    def required_header(headers); end
  end
end

Octokit::OneTimePasswordRequired::OTP_DELIVERY_PATTERN = T.let(T.unsafe(nil), Regexp)

class Octokit::Organization
  class << self
    def path(org); end
  end
end

Octokit::PATCH = T.let(T.unsafe(nil), Integer)

module Octokit::Preview
  def ensure_api_media_type(type, options); end
  def warn_preview(type); end
end

Octokit::Preview::PREVIEW_TYPES = T.let(T.unsafe(nil), Hash)

Octokit::RATE_LIMITED_ERRORS = T.let(T.unsafe(nil), Array)

class Octokit::RateLimit < ::Struct
  class << self
    def from_response(response); end
  end
end

class Octokit::RepoArguments < ::Octokit::Arguments
  def initialize(args); end

  def repo; end
end

class Octokit::Repository
  def initialize(repo); end

  def id; end
  def id=(_arg0); end
  def id_api_path; end
  def name; end
  def name=(_arg0); end
  def named_api_path; end
  def owner; end
  def owner=(_arg0); end
  def path; end
  def repo; end
  def slug; end
  def to_s; end
  def url; end
  def user; end
  def username; end

  private

  def raise_invalid_repository!(repo); end
  def validate_owner_and_name!(repo); end

  class << self
    def from_url(url); end
    def path(repo); end
  end
end

Octokit::Repository::NAME_WITH_OWNER_PATTERN = T.let(T.unsafe(nil), Regexp)

class Octokit::RepositoryUnavailable < ::Octokit::Forbidden
end

module Octokit::Response
end

class Octokit::Response::FeedParser < ::Faraday::Response::Middleware
  def on_complete(env); end
end

class Octokit::Response::RaiseError < ::Faraday::Response::Middleware
  def on_complete(response); end
end

class Octokit::SAMLProtected < ::Octokit::Forbidden
end

class Octokit::ServerError < ::Octokit::Error
end

class Octokit::ServiceUnavailable < ::Octokit::ServerError
end

class Octokit::TooLargeContent < ::Octokit::Forbidden
end

class Octokit::TooManyLoginAttempts < ::Octokit::Forbidden
end

class Octokit::TooManyRequests < ::Octokit::Forbidden
end

class Octokit::Unauthorized < ::Octokit::ClientError
end

class Octokit::UnavailableForLegalReasons < ::Octokit::ClientError
end

class Octokit::UnprocessableEntity < ::Octokit::ClientError
end

class Octokit::UnsupportedMediaType < ::Octokit::ClientError
end

class Octokit::UnverifiedEmail < ::Octokit::Forbidden
end

class Octokit::User
  class << self
    def path(user); end
  end
end

Octokit::VERSION = T.let(T.unsafe(nil), String)

module Octokit::Warnable
  def octokit_warn(*message); end
end
