# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `pghero` gem.
# Please instead update this file by running `bin/tapioca gem pghero`.


# pkg:gem/pghero#lib/pghero/methods/basic.rb:1
module PgHero
  class << self
    # pkg:gem/pghero#lib/pghero.rb:188
    def analyze_all(**options); end

    # pkg:gem/pghero#lib/pghero.rb:195
    def autoindex_all(create: T.unsafe(nil), verbose: T.unsafe(nil)); end

    # pkg:gem/pghero#lib/pghero.rb:40
    def cache_hit_rate_threshold; end

    # pkg:gem/pghero#lib/pghero.rb:40
    def cache_hit_rate_threshold=(_arg0); end

    # pkg:gem/pghero#lib/pghero.rb:173
    def capture_query_stats(verbose: T.unsafe(nil)); end

    # pkg:gem/pghero#lib/pghero.rb:181
    def capture_space_stats(verbose: T.unsafe(nil)); end

    # delete previous stats
    # go database by database to use an index
    # stats for old databases are not cleaned up since we can't use an index
    # TODO clean queries
    #
    # pkg:gem/pghero#lib/pghero.rb:210
    def clean_query_stats(before: T.unsafe(nil)); end

    # pkg:gem/pghero#lib/pghero.rb:216
    def clean_space_stats(before: T.unsafe(nil)); end

    # pkg:gem/pghero#lib/pghero.rb:97
    def config; end

    # pkg:gem/pghero#lib/pghero.rb:40
    def config_path; end

    # pkg:gem/pghero#lib/pghero.rb:40
    def config_path=(_arg0); end

    # ensure we only have one copy of databases
    # so there's only one connection pool per database
    #
    # pkg:gem/pghero#lib/pghero.rb:159
    def databases; end

    # private
    #
    # pkg:gem/pghero#lib/pghero.rb:130
    def default_config; end

    # pkg:gem/pghero#lib/pghero.rb:40
    def env; end

    # pkg:gem/pghero#lib/pghero.rb:40
    def env=(_arg0); end

    # private
    #
    # pkg:gem/pghero#lib/pghero.rb:80
    def explain_enabled?; end

    # private
    #
    # pkg:gem/pghero#lib/pghero.rb:85
    def explain_mode; end

    # pkg:gem/pghero#lib/pghero.rb:40
    def explain_timeout_sec; end

    # pkg:gem/pghero#lib/pghero.rb:40
    def explain_timeout_sec=(_arg0); end

    # private
    #
    # pkg:gem/pghero#lib/pghero.rb:102
    def file_config; end

    # pkg:gem/pghero#lib/pghero.rb:40
    def filter_data; end

    # pkg:gem/pghero#lib/pghero.rb:40
    def filter_data=(_arg0); end

    # pkg:gem/pghero#lib/pghero.rb:93
    def kill_enabled?; end

    # pkg:gem/pghero#lib/pghero.rb:40
    def long_running_query_sec; end

    # pkg:gem/pghero#lib/pghero.rb:40
    def long_running_query_sec=(_arg0); end

    # use method instead of attr_accessor to ensure
    # this works if variable set after PgHero is loaded
    #
    # pkg:gem/pghero#lib/pghero.rb:70
    def password; end

    # pkg:gem/pghero#lib/pghero.rb:202
    def pretty_size(value); end

    # pkg:gem/pghero#lib/pghero/engine.rb:3
    def railtie_helpers_paths; end

    # pkg:gem/pghero#lib/pghero/engine.rb:3
    def railtie_namespace; end

    # pkg:gem/pghero#lib/pghero/engine.rb:3
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # pkg:gem/pghero#lib/pghero.rb:40
    def show_migrations; end

    # pkg:gem/pghero#lib/pghero.rb:40
    def show_migrations=(_arg0); end

    # pkg:gem/pghero#lib/pghero.rb:40
    def slow_query_calls; end

    # pkg:gem/pghero#lib/pghero.rb:40
    def slow_query_calls=(_arg0); end

    # pkg:gem/pghero#lib/pghero.rb:40
    def slow_query_ms; end

    # pkg:gem/pghero#lib/pghero.rb:40
    def slow_query_ms=(_arg0); end

    # config pattern for https://github.com/ankane/pghero/issues/424
    #
    # pkg:gem/pghero#lib/pghero.rb:75
    def stats_database_url; end

    # pkg:gem/pghero#lib/pghero/engine.rb:3
    def table_name_prefix; end

    # pkg:gem/pghero#lib/pghero.rb:58
    def time_zone; end

    # pkg:gem/pghero#lib/pghero.rb:54
    def time_zone=(time_zone); end

    # pkg:gem/pghero#lib/pghero.rb:40
    def total_connections_threshold; end

    # pkg:gem/pghero#lib/pghero.rb:40
    def total_connections_threshold=(_arg0); end

    # pkg:gem/pghero#lib/pghero/engine.rb:3
    def use_relative_model_naming?; end

    # use method instead of attr_accessor to ensure
    # this works if variable set after PgHero is loaded
    #
    # pkg:gem/pghero#lib/pghero.rb:64
    def username; end

    # pkg:gem/pghero#lib/pghero.rb:89
    def visualize_url; end

    private

    # pkg:gem/pghero#lib/pghero.rb:224
    def each_database; end
  end
end

# pkg:gem/pghero#lib/pghero/connection.rb:2
class PgHero::Connection < ::ActiveRecord::Base
  include ::PgHero::Connection::GeneratedAttributeMethods
  include ::PgHero::Connection::GeneratedAssociationMethods

  class << self
    private

    # pkg:gem/pghero#lib/pghero/connection.rb:2
    def __class_attr__validators; end

    # pkg:gem/pghero#lib/pghero/connection.rb:2
    def __class_attr__validators=(new_value); end

    # pkg:gem/pghero#lib/pghero/connection.rb:2
    def __class_attr_defined_enums; end

    # pkg:gem/pghero#lib/pghero/connection.rb:2
    def __class_attr_defined_enums=(new_value); end
  end
end

# pkg:gem/pghero#lib/pghero/connection.rb:2
module PgHero::Connection::GeneratedAssociationMethods; end

# pkg:gem/pghero#lib/pghero/connection.rb:2
module PgHero::Connection::GeneratedAttributeMethods; end

# pkg:gem/pghero#lib/pghero/database.rb:2
class PgHero::Database
  include ::PgHero::Methods::Basic
  include ::PgHero::Methods::Connections
  include ::PgHero::Methods::Constraints
  include ::PgHero::Methods::Explain
  include ::PgHero::Methods::Indexes
  include ::PgHero::Methods::Kill
  include ::PgHero::Methods::Maintenance
  include ::PgHero::Methods::Queries
  include ::PgHero::Methods::QueryStats
  include ::PgHero::Methods::Replication
  include ::PgHero::Methods::Sequences
  include ::PgHero::Methods::Settings
  include ::PgHero::Methods::Space
  include ::PgHero::Methods::SuggestedIndexes
  include ::PgHero::Methods::System
  include ::PgHero::Methods::Tables

  # pkg:gem/pghero#lib/pghero/database.rb:22
  def initialize(id, config); end

  # pkg:gem/pghero#lib/pghero/database.rb:72
  def aws_access_key_id; end

  # environment variable is only used if no config file
  #
  # pkg:gem/pghero#lib/pghero/database.rb:85
  def aws_db_instance_identifier; end

  # pkg:gem/pghero#lib/pghero/database.rb:80
  def aws_region; end

  # pkg:gem/pghero#lib/pghero/database.rb:76
  def aws_secret_access_key; end

  # pkg:gem/pghero#lib/pghero/database.rb:40
  def cache_hit_rate_threshold; end

  # pkg:gem/pghero#lib/pghero/database.rb:36
  def capture_query_stats?; end

  # pkg:gem/pghero#lib/pghero/database.rb:20
  def config; end

  # pkg:gem/pghero#lib/pghero/database.rb:56
  def explain_timeout_sec; end

  # must check keys for booleans
  #
  # pkg:gem/pghero#lib/pghero/database.rb:95
  def filter_data; end

  # environment variable is only used if no config file
  #
  # pkg:gem/pghero#lib/pghero/database.rb:90
  def gcp_database_id; end

  # pkg:gem/pghero#lib/pghero/database.rb:20
  def id; end

  # pkg:gem/pghero#lib/pghero/database.rb:68
  def index_bloat_bytes; end

  # pkg:gem/pghero#lib/pghero/database.rb:60
  def long_running_query_sec; end

  # pkg:gem/pghero#lib/pghero/database.rb:32
  def name; end

  # pkg:gem/pghero#lib/pghero/database.rb:52
  def slow_query_calls; end

  # pkg:gem/pghero#lib/pghero/database.rb:48
  def slow_query_ms; end

  # pkg:gem/pghero#lib/pghero/database.rb:44
  def total_connections_threshold; end

  # pkg:gem/pghero#lib/pghero/database.rb:64
  def unused_index_bytes; end

  private

  # just return the model
  # do not start a connection
  #
  # pkg:gem/pghero#lib/pghero/database.rb:137
  def build_connection_model; end

  # check adapter lazily
  #
  # pkg:gem/pghero#lib/pghero/database.rb:121
  def connection_model; end
end

# pkg:gem/pghero#lib/pghero/engine.rb:2
class PgHero::Engine < ::Rails::Engine; end

# pkg:gem/pghero#lib/pghero.rb:33
class PgHero::Error < ::StandardError; end

class PgHero::HomeController < ::ActionController::Base
  def connection_stats; end
  def connections; end
  def cpu_usage; end
  def enable_query_stats; end
  def explain; end
  def free_space_stats; end
  def index; end
  def index_bloat; end
  def kill; end
  def kill_all; end
  def kill_long_running_queries; end
  def live_queries; end
  def load_stats; end
  def maintenance; end
  def queries; end
  def relation_space; end
  def replication_lag_stats; end
  def reset_query_stats; end
  def show_query; end
  def space; end
  def system; end
  def tune; end

  protected

  def chart_library_options; end
  def check_api; end
  def check_server_version; end
  def default_url_options; end
  def ensure_kill_enabled; end
  def ensure_query_stats; end
  def group_connections(connections, keys); end
  def group_connections_by_key(connections, key); end
  def redirect_backward(**options); end
  def render_text(message, status:); end
  def rescue_timeout(default); end
  def set_database; end
  def set_query_stats_enabled; end
  def set_show_details; end
  def set_suggested_indexes(min_average_time = T.unsafe(nil), min_calls = T.unsafe(nil)); end
  def system_params; end

  private

  def _layout(lookup_context, formats, keys); end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__layout; end
    def __class_attr__layout=(new_value); end
    def __class_attr__layout_conditions; end
    def __class_attr__layout_conditions=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

module PgHero::HomeController::HelperMethods
  include ::ActionController::Base::HelperMethods
  include ::PgHero::HomeHelper
end

module PgHero::HomeHelper
  def pghero_formatted_date_time(time); end
  def pghero_formatted_vacuum_times(time); end
  def pghero_js_value(value); end
  def pghero_pretty_ident(table, schema: T.unsafe(nil)); end
  def pghero_remove_index(query); end
end

# pkg:gem/pghero#lib/pghero.rb:36
PgHero::MUTEX = T.let(T.unsafe(nil), Thread::Mutex)

# pkg:gem/pghero#lib/pghero/methods/basic.rb:2
module PgHero::Methods; end

# pkg:gem/pghero#lib/pghero/methods/basic.rb:3
module PgHero::Methods::Basic
  # pkg:gem/pghero#lib/pghero/methods/basic.rb:21
  def current_user; end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:17
  def database_name; end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:33
  def quote_ident(value); end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:25
  def server_version; end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:29
  def server_version_num; end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:4
  def ssl_used?; end

  private

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:115
  def execute(sql, binds = T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:39
  def prepare_sql(sql, binds = T.unsafe(nil), stats: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:130
  def quote_column_name(value); end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:126
  def quote_table_name(value); end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:50
  def select_all(sql, binds = T.unsafe(nil), stats: T.unsafe(nil), query_columns: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:57
  def select_all_leased(sql, conn:, query_columns:); end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:103
  def select_all_size(sql, binds = T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:99
  def select_all_stats(sql, binds = T.unsafe(nil), **options); end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:111
  def select_one(sql, binds = T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:151
  def table_exists?(table); end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:134
  def unquote(part); end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:121
  def with_connection(stats: T.unsafe(nil), &block); end

  # pkg:gem/pghero#lib/pghero/methods/basic.rb:142
  def with_transaction(lock_timeout: T.unsafe(nil), statement_timeout: T.unsafe(nil), rollback: T.unsafe(nil)); end
end

# pkg:gem/pghero#lib/pghero/methods/connections.rb:3
module PgHero::Methods::Connections
  # pkg:gem/pghero#lib/pghero/methods/connections.rb:43
  def connection_sources; end

  # pkg:gem/pghero#lib/pghero/methods/connections.rb:27
  def connection_states; end

  # pkg:gem/pghero#lib/pghero/methods/connections.rb:4
  def connections; end

  # pkg:gem/pghero#lib/pghero/methods/connections.rb:23
  def total_connections; end
end

# pkg:gem/pghero#lib/pghero/methods/constraints.rb:3
module PgHero::Methods::Constraints
  # referenced fields can be nil
  # as not all constraints are foreign keys
  #
  # pkg:gem/pghero#lib/pghero/methods/constraints.rb:6
  def invalid_constraints; end
end

# pkg:gem/pghero#lib/pghero/methods/explain.rb:3
module PgHero::Methods::Explain
  # note: this method is not affected by the explain option
  #
  # pkg:gem/pghero#lib/pghero/methods/explain.rb:5
  def explain(sql, analyze: T.unsafe(nil), verbose: T.unsafe(nil), costs: T.unsafe(nil), settings: T.unsafe(nil), generic_plan: T.unsafe(nil), buffers: T.unsafe(nil), wal: T.unsafe(nil), timing: T.unsafe(nil), summary: T.unsafe(nil), format: T.unsafe(nil)); end

  private

  # pkg:gem/pghero#lib/pghero/methods/explain.rb:41
  def add_explain_option(options, name, value); end

  # important! validate format to prevent injection
  #
  # pkg:gem/pghero#lib/pghero/methods/explain.rb:48
  def explain_format(format); end

  # pkg:gem/pghero#lib/pghero/methods/explain.rb:34
  def explain_safe?; end
end

# pkg:gem/pghero#lib/pghero/methods/indexes.rb:3
module PgHero::Methods::Indexes
  # pkg:gem/pghero#lib/pghero/methods/indexes.rb:173
  def duplicate_indexes(indexes: T.unsafe(nil)); end

  # https://gist.github.com/mbanck/9976015/71888a24e464e2f772182a7eb54f15a125edf398
  # thanks @jberkus and @mbanck
  #
  # pkg:gem/pghero#lib/pghero/methods/indexes.rb:189
  def index_bloat(min_size: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/indexes.rb:13
  def index_caching; end

  # pkg:gem/pghero#lib/pghero/methods/indexes.rb:4
  def index_hit_rate; end

  # pkg:gem/pghero#lib/pghero/methods/indexes.rb:31
  def index_usage; end

  # TODO parse array properly
  # https://stackoverflow.com/questions/2204058/list-columns-with-indexes-in-postgresql
  #
  # pkg:gem/pghero#lib/pghero/methods/indexes.rb:130
  def indexes; end

  # pkg:gem/pghero#lib/pghero/methods/indexes.rb:119
  def invalid_indexes(indexes: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/indexes.rb:108
  def last_stats_reset_time; end

  # pkg:gem/pghero#lib/pghero/methods/indexes.rb:49
  def missing_indexes; end

  # pkg:gem/pghero#lib/pghero/methods/indexes.rb:103
  def reset_stats; end

  # pkg:gem/pghero#lib/pghero/methods/indexes.rb:71
  def unused_indexes(max_scans: T.unsafe(nil), min_size: T.unsafe(nil), across: T.unsafe(nil)); end

  protected

  # pkg:gem/pghero#lib/pghero/methods/indexes.rb:330
  def index_covers?(indexed_columns, columns); end
end

# pkg:gem/pghero#lib/pghero/methods/kill.rb:3
module PgHero::Methods::Kill
  # note: this method is not affected by disable_kill option
  #
  # pkg:gem/pghero#lib/pghero/methods/kill.rb:5
  def kill(pid); end

  # note: this method is not affected by disable_kill option
  #
  # pkg:gem/pghero#lib/pghero/methods/kill.rb:16
  def kill_all; end

  # note: this method is not affected by disable_kill option
  #
  # pkg:gem/pghero#lib/pghero/methods/kill.rb:10
  def kill_long_running_queries(min_duration: T.unsafe(nil)); end
end

# pkg:gem/pghero#lib/pghero/methods/maintenance.rb:3
module PgHero::Methods::Maintenance
  # pkg:gem/pghero#lib/pghero/methods/maintenance.rb:64
  def analyze(table, verbose: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/maintenance.rb:69
  def analyze_tables(verbose: T.unsafe(nil), min_size: T.unsafe(nil), tables: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/maintenance.rb:29
  def autovacuum_danger; end

  # pkg:gem/pghero#lib/pghero/methods/maintenance.rb:46
  def maintenance_info; end

  # https://www.postgresql.org/docs/current/routine-vacuuming.html#VACUUM-FOR-WRAPAROUND
  # "the system will shut down and refuse to start any new transactions
  # once there are fewer than 1 million transactions left until wraparound"
  # warn when 10,000,000 transactions left
  #
  # pkg:gem/pghero#lib/pghero/methods/maintenance.rb:8
  def transaction_id_danger(threshold: T.unsafe(nil), max_value: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/maintenance.rb:34
  def vacuum_progress; end
end

# pkg:gem/pghero#lib/pghero/methods/queries.rb:3
module PgHero::Methods::Queries
  # from https://wiki.postgresql.org/wiki/Lock_Monitoring
  # and https://big-elephants.com/2013-09/exploring-query-locks-in-postgres/
  #
  # pkg:gem/pghero#lib/pghero/methods/queries.rb:40
  def blocked_queries; end

  # pkg:gem/pghero#lib/pghero/methods/queries.rb:34
  def long_running_queries; end

  # pkg:gem/pghero#lib/pghero/methods/queries.rb:4
  def running_queries(min_duration: T.unsafe(nil), all: T.unsafe(nil)); end
end

# pkg:gem/pghero#lib/pghero/methods/query_stats.rb:3
module PgHero::Methods::QueryStats
  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:138
  def capture_query_stats(raise_errors: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:146
  def clean_query_stats(before: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:88
  def disable_query_stats; end

  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:83
  def enable_query_stats; end

  # https://stackoverflow.com/questions/20582500/how-to-check-if-a-table-exists-in-a-given-schema
  #
  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:124
  def historical_query_stats_enabled?; end

  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:130
  def queries_table_exists?; end

  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:156
  def query_hash_stats(query_hash, user: T.unsafe(nil), current: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:4
  def query_stats(current: T.unsafe(nil), historical: T.unsafe(nil), limit: T.unsafe(nil), sort: T.unsafe(nil), user: T.unsafe(nil), query_hash: T.unsafe(nil), start_at: T.unsafe(nil), end_at: T.unsafe(nil), min_average_time: T.unsafe(nil), min_calls: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:63
  def query_stats_available?; end

  # only cache if true
  #
  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:68
  def query_stats_enabled?; end

  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:72
  def query_stats_extension_enabled?; end

  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:76
  def query_stats_readable?; end

  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:134
  def query_stats_table_exists?; end

  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:93
  def reset_query_stats(user: T.unsafe(nil), query_hash: T.unsafe(nil), raise_errors: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:151
  def slow_queries(query_stats: T.unsafe(nil), **options); end

  private

  # duplicates are fine, but could use advisory lock to prevent them
  #
  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:372
  def add_queries(queries); end

  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:336
  def combine_query_stats(grouped_stats); end

  # https://www.craigkerstiens.com/2013/01/10/more-on-postgres-performance/
  #
  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:205
  def current_query_stats(limit: T.unsafe(nil), sort: T.unsafe(nil), user: T.unsafe(nil), query_hash: T.unsafe(nil), origin: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:348
  def explainable?(query); end

  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:263
  def historical_query_stats(limit: T.unsafe(nil), sort: T.unsafe(nil), user: T.unsafe(nil), query_hash: T.unsafe(nil), start_at: T.unsafe(nil), end_at: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/query_stats.rb:352
  def insert_query_stats(query_stats, captured_at); end
end

# pkg:gem/pghero#lib/pghero/methods/replication.rb:3
module PgHero::Methods::Replication
  # pkg:gem/pghero#lib/pghero/methods/replication.rb:4
  def replica?; end

  # pkg:gem/pghero#lib/pghero/methods/replication.rb:37
  def replicating?; end

  # https://www.postgresql.org/message-id/CADKbJJWz9M0swPT3oqe8f9+tfD4-F54uE6Xtkh4nERpVsQnjnw@mail.gmail.com
  #
  # pkg:gem/pghero#lib/pghero/methods/replication.rb:12
  def replication_lag; end

  # pkg:gem/pghero#lib/pghero/methods/replication.rb:25
  def replication_slots; end

  private

  # pkg:gem/pghero#lib/pghero/methods/replication.rb:45
  def feature_support; end

  # pkg:gem/pghero#lib/pghero/methods/replication.rb:49
  def with_feature_support(cache_key, default = T.unsafe(nil)); end
end

# pkg:gem/pghero#lib/pghero/methods/sequences.rb:3
module PgHero::Methods::Sequences
  # pkg:gem/pghero#lib/pghero/methods/sequences.rb:81
  def sequence_danger(threshold: T.unsafe(nil), sequences: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/sequences.rb:4
  def sequences; end

  private

  # adds readable attribute to all sequences
  # also adds schema if missing
  #
  # pkg:gem/pghero#lib/pghero/methods/sequences.rb:112
  def add_sequence_attributes(sequences); end

  # can parse
  # nextval('id_seq'::regclass)
  # nextval(('id_seq'::text)::regclass)
  #
  # pkg:gem/pghero#lib/pghero/methods/sequences.rb:91
  def parse_default_value(default_value); end

  # pkg:gem/pghero#lib/pghero/methods/sequences.rb:101
  def unquote_ident(value); end
end

# pkg:gem/pghero#lib/pghero/methods/settings.rb:3
module PgHero::Methods::Settings
  # pkg:gem/pghero#lib/pghero/methods/settings.rb:24
  def autovacuum_settings; end

  # pkg:gem/pghero#lib/pghero/methods/settings.rb:4
  def settings; end

  # pkg:gem/pghero#lib/pghero/methods/settings.rb:28
  def vacuum_settings; end

  private

  # pkg:gem/pghero#lib/pghero/methods/settings.rb:34
  def fetch_settings(names); end
end

# pkg:gem/pghero#lib/pghero/methods/space.rb:3
module PgHero::Methods::Space
  # pkg:gem/pghero#lib/pghero/methods/space.rb:125
  def capture_space_stats; end

  # pkg:gem/pghero#lib/pghero/methods/space.rb:140
  def clean_space_stats(before: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/space.rb:4
  def database_size; end

  # pkg:gem/pghero#lib/pghero/methods/space.rb:8
  def relation_sizes; end

  # pkg:gem/pghero#lib/pghero/methods/space.rb:93
  def relation_space_stats(relation, schema: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/space.rb:49
  def space_growth(days: T.unsafe(nil), relation_sizes: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/space.rb:145
  def space_stats_enabled?; end

  # pkg:gem/pghero#lib/pghero/methods/space.rb:29
  def table_sizes; end
end

# pkg:gem/pghero#lib/pghero/methods/suggested_indexes.rb:3
module PgHero::Methods::SuggestedIndexes
  # pkg:gem/pghero#lib/pghero/methods/suggested_indexes.rb:78
  def autoindex(create: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/suggested_indexes.rb:89
  def best_index(statement); end

  # pkg:gem/pghero#lib/pghero/methods/suggested_indexes.rb:64
  def suggested_indexes(suggested_indexes_by_query: T.unsafe(nil), **options); end

  # TODO clean this mess
  #
  # pkg:gem/pghero#lib/pghero/methods/suggested_indexes.rb:9
  def suggested_indexes_by_query(queries: T.unsafe(nil), query_stats: T.unsafe(nil), indexes: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/suggested_indexes.rb:4
  def suggested_indexes_enabled?; end

  private

  # pkg:gem/pghero#lib/pghero/methods/suggested_indexes.rb:95
  def best_index_helper(statements); end

  # pkg:gem/pghero#lib/pghero/methods/suggested_indexes.rb:198
  def best_index_structure(statement); end

  # pkg:gem/pghero#lib/pghero/methods/suggested_indexes.rb:311
  def column_stats(schema: T.unsafe(nil), table: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/suggested_indexes.rb:302
  def parse_sort(sort_clause); end

  # pkg:gem/pghero#lib/pghero/methods/suggested_indexes.rb:271
  def parse_table(tree); end

  # TODO capture values
  #
  # pkg:gem/pghero#lib/pghero/methods/suggested_indexes.rb:283
  def parse_where(tree); end

  # TODO better row estimation
  # https://www.postgresql.org/docs/current/static/row-estimation-examples.html
  #
  # pkg:gem/pghero#lib/pghero/methods/suggested_indexes.rb:239
  def row_estimates(stats, total_rows, rows_left, op); end
end

# pkg:gem/pghero#lib/pghero/methods/system.rb:3
module PgHero::Methods::System
  # pkg:gem/pghero#lib/pghero/methods/system.rb:20
  def connection_stats(**options); end

  # pkg:gem/pghero#lib/pghero/methods/system.rb:16
  def cpu_usage(**options); end

  # pkg:gem/pghero#lib/pghero/methods/system.rb:36
  def free_space_stats(**options); end

  # pkg:gem/pghero#lib/pghero/methods/system.rb:40
  def rds_stats(metric_name, duration: T.unsafe(nil), period: T.unsafe(nil), offset: T.unsafe(nil), series: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/system.rb:28
  def read_iops_stats(**options); end

  # pkg:gem/pghero#lib/pghero/methods/system.rb:24
  def replication_lag_stats(**options); end

  # pkg:gem/pghero#lib/pghero/methods/system.rb:4
  def system_stats_enabled?; end

  # pkg:gem/pghero#lib/pghero/methods/system.rb:8
  def system_stats_provider; end

  # pkg:gem/pghero#lib/pghero/methods/system.rb:32
  def write_iops_stats(**options); end

  private

  # pkg:gem/pghero#lib/pghero/methods/system.rb:203
  def add_missing_data(data, start_time, end_time, period); end

  # only use data points included in both series
  # this also eliminates need to align Time.now
  #
  # pkg:gem/pghero#lib/pghero/methods/system.rb:195
  def free_space(quota, used); end

  # pkg:gem/pghero#lib/pghero/methods/system.rb:80
  def gcp_stats(metric_name, duration: T.unsafe(nil), period: T.unsafe(nil), offset: T.unsafe(nil), series: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/system.rb:161
  def system_stats(metric_key, **options); end
end

# pkg:gem/pghero#lib/pghero/methods/tables.rb:3
module PgHero::Methods::Tables
  # pkg:gem/pghero#lib/pghero/methods/tables.rb:13
  def table_caching; end

  # pkg:gem/pghero#lib/pghero/methods/tables.rb:4
  def table_hit_rate; end

  # pkg:gem/pghero#lib/pghero/methods/tables.rb:46
  def table_stats(schema: T.unsafe(nil), table: T.unsafe(nil)); end

  # pkg:gem/pghero#lib/pghero/methods/tables.rb:30
  def unused_tables; end
end

# pkg:gem/pghero#lib/pghero.rb:34
class PgHero::NotEnabled < ::PgHero::Error; end

# pkg:gem/pghero#lib/pghero/query.rb:2
class PgHero::Query < ::PgHero::Stats
  include ::PgHero::Query::GeneratedAttributeMethods
  include ::PgHero::Query::GeneratedAssociationMethods

  # pkg:gem/pghero#lib/pghero/query.rb:6
  def _run_create_callbacks(&block); end

  # pkg:gem/pghero#lib/pghero/query.rb:6
  def _run_save_callbacks(&block); end

  # pkg:gem/pghero#lib/pghero/query.rb:6
  def _run_update_callbacks(&block); end

  # pkg:gem/pghero#lib/pghero/query.rb:6
  def autosave_associated_records_for_query_stats(*args); end

  # pkg:gem/pghero#lib/pghero/query.rb:6
  def validate_associated_records_for_query_stats(*args); end

  class << self
    private

    # pkg:gem/pghero#lib/pghero/query.rb:6
    def __class_attr___callbacks; end

    # pkg:gem/pghero#lib/pghero/query.rb:6
    def __class_attr___callbacks=(new_value); end

    # pkg:gem/pghero#lib/pghero/query.rb:6
    def __class_attr__reflections; end

    # pkg:gem/pghero#lib/pghero/query.rb:6
    def __class_attr__reflections=(new_value); end

    # pkg:gem/pghero#lib/pghero/query.rb:2
    def __class_attr__validators; end

    # pkg:gem/pghero#lib/pghero/query.rb:2
    def __class_attr__validators=(new_value); end

    # pkg:gem/pghero#lib/pghero/query.rb:2
    def __class_attr_defined_enums; end

    # pkg:gem/pghero#lib/pghero/query.rb:2
    def __class_attr_defined_enums=(new_value); end
  end
end

# pkg:gem/pghero#lib/pghero/query.rb:2
module PgHero::Query::GeneratedAssociationMethods
  # pkg:gem/pghero#lib/pghero/query.rb:6
  def query_stat_ids; end

  # pkg:gem/pghero#lib/pghero/query.rb:6
  def query_stat_ids=(ids); end

  # pkg:gem/pghero#lib/pghero/query.rb:6
  def query_stats; end

  # pkg:gem/pghero#lib/pghero/query.rb:6
  def query_stats=(value); end
end

# pkg:gem/pghero#lib/pghero/query.rb:2
module PgHero::Query::GeneratedAttributeMethods; end

# pkg:gem/pghero#lib/pghero/query_stats.rb:2
class PgHero::QueryStats < ::PgHero::Stats
  include ::PgHero::QueryStats::GeneratedAttributeMethods
  include ::PgHero::QueryStats::GeneratedAssociationMethods

  class << self
    private

    # pkg:gem/pghero#lib/pghero/query_stats.rb:2
    def __class_attr__validators; end

    # pkg:gem/pghero#lib/pghero/query_stats.rb:2
    def __class_attr__validators=(new_value); end

    # pkg:gem/pghero#lib/pghero/query_stats.rb:2
    def __class_attr_defined_enums; end

    # pkg:gem/pghero#lib/pghero/query_stats.rb:2
    def __class_attr_defined_enums=(new_value); end
  end
end

# pkg:gem/pghero#lib/pghero/query_stats.rb:2
module PgHero::QueryStats::GeneratedAssociationMethods; end

# pkg:gem/pghero#lib/pghero/query_stats.rb:2
module PgHero::QueryStats::GeneratedAttributeMethods; end

# pkg:gem/pghero#lib/pghero/space_stats.rb:2
class PgHero::SpaceStats < ::PgHero::Stats
  include ::PgHero::SpaceStats::GeneratedAttributeMethods
  include ::PgHero::SpaceStats::GeneratedAssociationMethods

  class << self
    private

    # pkg:gem/pghero#lib/pghero/space_stats.rb:2
    def __class_attr__validators; end

    # pkg:gem/pghero#lib/pghero/space_stats.rb:2
    def __class_attr__validators=(new_value); end

    # pkg:gem/pghero#lib/pghero/space_stats.rb:2
    def __class_attr_defined_enums; end

    # pkg:gem/pghero#lib/pghero/space_stats.rb:2
    def __class_attr_defined_enums=(new_value); end
  end
end

# pkg:gem/pghero#lib/pghero/space_stats.rb:2
module PgHero::SpaceStats::GeneratedAssociationMethods; end

# pkg:gem/pghero#lib/pghero/space_stats.rb:2
module PgHero::SpaceStats::GeneratedAttributeMethods; end

# pkg:gem/pghero#lib/pghero/stats.rb:2
class PgHero::Stats < ::ActiveRecord::Base
  include ::PgHero::Stats::GeneratedAttributeMethods
  include ::PgHero::Stats::GeneratedAssociationMethods

  class << self
    private

    # pkg:gem/pghero#lib/pghero/stats.rb:2
    def __class_attr__validators; end

    # pkg:gem/pghero#lib/pghero/stats.rb:2
    def __class_attr__validators=(new_value); end

    # pkg:gem/pghero#lib/pghero/stats.rb:2
    def __class_attr_defined_enums; end

    # pkg:gem/pghero#lib/pghero/stats.rb:2
    def __class_attr_defined_enums=(new_value); end
  end
end

# pkg:gem/pghero#lib/pghero/stats.rb:2
module PgHero::Stats::GeneratedAssociationMethods; end

# pkg:gem/pghero#lib/pghero/stats.rb:2
module PgHero::Stats::GeneratedAttributeMethods; end

# pkg:gem/pghero#lib/pghero/version.rb:2
PgHero::VERSION = T.let(T.unsafe(nil), String)
