# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rspec-rails` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

module RSpec
end

module RSpec::Rails
end

module RSpec::Rails::FeatureCheck

  private

  def has_action_cable_testing?; end
  def has_action_mailbox?; end
  def has_action_mailer?; end
  def has_action_mailer_parameterized?; end
  def has_action_mailer_preview?; end
  def has_action_mailer_unified_delivery?; end
  def has_active_job?; end
  def has_active_record?; end
  def has_active_record_migration?; end
  def type_metatag(type); end

  class << self
    def has_action_cable_testing?; end
    def has_action_mailbox?; end
    def has_action_mailer?; end
    def has_action_mailer_parameterized?; end
    def has_action_mailer_preview?; end
    def has_action_mailer_unified_delivery?; end
    def has_active_job?; end
    def has_active_record?; end
    def has_active_record_migration?; end
    def type_metatag(type); end
  end
end

class RSpec::Rails::Railtie < ::Rails::Railtie

  private

  def config_default_preview_path(options); end
  def config_preview_path?(options); end
  def setup_preview_path(app); end
  def supports_action_mailer_previews?(config); end
end
