# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'

Rails.application.load_tasks

namespace :heroku do
  desc 'Heroku release tasks (runs on every code push, before postdeploy task on review app creation)'
  task release: :environment do
    unless ActiveRecord::SchemaMigration.table_exists?
      Rails.logger.info "Database not initialized, skipping release tasks..."
      next
    end

    Rake::Task['db:migrate'].invoke
  end

  desc 'Heroku postdeploy tasks (runs only on review app creation, after release task)'
  task postdeploy: :environment do
    Rake::Task['db:schema:load'].invoke
    Rake::Task['db:seed'].invoke
  end
end

def remove_version_from_schema_rb
  puts "GoodJob: Sanitizing Rails version from schema.rb...\n"
  schema_rb = Rails.root.join("db/schema.rb").to_s
  contents = File.read(schema_rb)
  contents.sub!(/ActiveRecord::Schema\[\d\.\d\]/, "ActiveRecord::Schema")
  File.write(schema_rb, contents)
end

Rake::Task['db:migrate'].enhance do
  remove_version_from_schema_rb
end
Rake::Task['db:rollback'].enhance do
  remove_version_from_schema_rb
end
