---
glob: "**/*.erb"
linters:
  HardCodedString:
    enabled: false
  ClosingErbTagIndent:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/ArgumentAlignment:
        Enabled: false
      Layout/FirstHashElementIndentation:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/LeadingEmptyLines:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false


