name: Backlog
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  add_to_backlog:
    name: "Add to Project Board"
    runs-on: ubuntu-latest
    env:
      gh_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: 'Project v1: Add Issue'
        if: ${{ github.event_name == 'issues' && env.gh_token }}
        uses: alex-page/github-project-automation-plus@1f8873e97e3c8f58161a323b7c568c1f623a1c4d
        with:
          project: Backlog
          column: Inbox
          repo-token: ${{ env.gh_token }}

      - name: "Project v1: Add Pull Request"
        if: ${{ github.event_name == 'pull_request' && env.gh_token }}
        uses: alex-page/github-project-automation-plus@1f8873e97e3c8f58161a323b7c568c1f623a1c4d
        with:
          project: Backlog
          column: In progress
          repo-token: ${{ env.gh_token }}

      - name: 'Project v2: Add Issue'
        if: ${{ github.event_name == 'issues' && env.gh_token }}
        uses: actions/add-to-project@960fbad431afda394cfcf8743445e741acd19e85
        with:
          project-url: https://github.com/users/bensheldon/projects/3
          github-token: ${{ env.gh_token }}

      - name: "Project v2: Add Pull Request"
        if: ${{ github.event_name == 'pull_request' && env.gh_token }}
        uses: actions/add-to-project@960fbad431afda394cfcf8743445e741acd19e85
        with:
          project-url: https://github.com/users/bensheldon/projects/3
          github-token: ${{ env.gh_token }}
