name: Backlog
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  add_to_backlog:
    name: "Add to Backlog Project Board"
    runs-on: ubuntu-latest
    steps:
      - name: 'Add Issue'
        if: ${{ github.event_name == 'issue' }}
        uses: alex-page/github-project-automation-plus@9a05133
        with:
          project: Backlog
          column: Inbox
          repo-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: "Add Pull Request"
        if: ${{ github.event_name == 'pull_request' }}
        uses: alex-page/github-project-automation-plus@9a05133
        with:
          project: Backlog
          column: In progress
          repo-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
